### ISSUE TITLE
BETA testing next update

### ISSUE THREAD

**Issue by Chuckleberry-Finn** [TEHE-Studios/ExpandedHelicopterEvents#102]
### Private BETA testing needed.

Overall there isn't one thing to look out for. While getting a mix of SP and MP testers would be ideal, MP is a bit more of a focus.

Specifically if event audio is getting stuck.

A significant change was also done to targeting under the hood - but it should still work as expected. It was changed to use a heatmap style system to target player activity more so than random.

## [BETA](https://steamcommunity.com/sharedfiles/filedetails/?id=2921678847)
To access the workshop page on steam type this into your browser: 
`steam://openurl/https://steamcommunity.com/sharedfiles/filedetails/?id=2921678847`

**Comment by KittyKatx3** [comment]
Hey, I would be interested

**Comment by ChuckTheSheep** [comment]
Hello, the link can be found here: https://steamcommunity.com/sharedfiles/filedetails/?id=2921678847
We're looking for MP testing.

**Comment by KittyKatx3** [comment]
And how I can I report eventually bugs? In the GitHub?

**Comment by KittyKatx3** [comment]
Is there anything new that I should be looking in?

**Comment by ChuckTheSheep** [comment]
There has been changes done throughout the mod, the biggest thing to look out for is if events' audio is getting stuck still.

There's also been a significant change done to targeting - so it should still work as expected.

**Comment by KittyKatx3** [comment]
For how many days? And how I can report back to you? How many players in the server do you judged to be necessary?

**Comment by ChuckTheSheep** [comment]
You can use it for however many days you want, with as many players over 2.

**Comment by Ruikio** [comment]
How does one get this mod to show up in the workshop so I can download it? I'll throw it on my server with friends to test.

Is it okay if I remove current Expanded Helicopter Events from my server and plug in the beta? Sorry for the question. I went into the discussions and this wasn't in a FAQ. The FAQ seemed to be missing in general actually. Q&A only had some questions.

**Comment by ChuckTheSheep** [comment]
You should be able to access the workshop page using the above link. If not let me know.

The modID is on the workshop page, as well as the normal means to subscribe.

**Comment by Ruikio** [comment]
How do I get the link to be brought over to the Steam client? Clicking the link only b rings me to the browser.

**Comment by ChuckTheSheep** [comment]
I updated the description that should help.

**Comment by leonardofelin** [comment]
Hi, tested the beta version on a dedicated server. Event audio still gets stuck sometimes.
