### ISSUE TITLE
Sound loop issue

### ISSUE THREAD

**Issue by S4vrk** [TEHE-Studios/ExpandedHelicopterEvents#105]
**Describe the bug**
Whenever on a multiplayer server, the player that isn't the host has this bug of sounds like planes flying ahead, air raid sirens never stopping.
This is only fixed with a rejoin, until a sound happens again.

**To Reproduce**
Start a server with this mod in multiplayer with someone else, wait for a plane to fly overhead, it has a chance for the sound to never end.

**Comment by ChuckTheSheep** [comment]
Duplicate of #85
