### ISSUE TITLE
Permission to make a submod

### ISSUE THREAD

**Issue by huelman125** [TEHE-Studios/ExpandedHelicopterEvents#106]
Hi, this isn't really an issue but i didn't know where else to write this, me and another modder named Lemes are making a mod reskinning the helicopters. I am commenting here to ask for your permission to publish it. The original EHE will be a requirement on steam.

Here's a preview of our work.
![helicopters](https://user-images.githubusercontent.com/123581476/214635004-cbec950d-9264-4894-bea3-724df409ec27.png)

**Comment by ChuckTheSheep** [comment]
As long as the main mod is set as a requirement there is no issue. Good luck, and let us know when it's released as we can add your mod onto the sub-mod list. 👍
