### ISSUE TITLE
My server doesn’t show the helicopter event 

### ISSUE THREAD

**Issue by KittyKatx3** [TEHE-Studios/ExpandedHelicopterEvents#107]
Hey, so my server is pretty old, but since the beginning of it, it never really showed your mod, but others runs did. I opened the game with -debug, but I was wondering if I can trigger some tipe of event in my host game? (I always put everything insane, check the box of “continue scheduling forever” and uncheck the other, but I really wanna show my friends how your mod works :/

**Comment by chedaki** [comment]
Same here, freshly wiped server I set the jet event to be common (parameter is 4) but still nothing happened after 10 in game days

**Comment by KittyKatx3** [comment]
> Same here, freshly wiped server I set the jet event to be common (parameter is 4) but still nothing happened after 10 in game days

I always put everything in insane, but nothing really happened 
Opened another host game in other pc (mine this time, I was using my husband’s because it’s better) and this time works fine, but I really didn’t wanna give up my old server :/

**Comment by chedaki** [comment]
I checked server logs and this is all I have from this mod:

`LOG  : Mod         , 1674733388485> 12,675,605> loading ExpandedHelicopterEvents
LOG  : Mod         , 1674733388488> 12,675,608> mod "ExpandedHelicopterEvents" overrides media/clothing/clothingitems/hat_sphhelmet.xml
LOG  : Mod         , 1674733388488> 12,675,608> mod "ExpandedHelicopterEvents" overrides media/clothing/clothing.xml
LOG  : Mod         , 1674733388492> 12,675,612> mod "ExpandedHelicopterEvents" overrides media/fileguidtable.xml
LOG  : Mod         , 1674733388493> 12,675,613> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/cs/tooltip_cs.txt
LOG  : Mod         , 1674733388493> 12,675,613> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/cs/itemname_cs.txt
LOG  : Mod         , 1674733388493> 12,675,613> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/cs/ig_ui_cs.txt
LOG  : Mod         , 1674733388493> 12,675,613> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/cs/sandbox_cs.txt
LOG  : Mod         , 1674733388493> 12,675,613> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/cs/contextmenu_cs.txt
LOG  : Mod         , 1674733388493> 12,675,613> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/cs/dynamicradio_cs.txt
LOG  : Mod         , 1674733388494> 12,675,614> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/fr/dynamicradio_fr.txt
LOG  : Mod         , 1674733388494> 12,675,614> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/fr/items_fr.txt
LOG  : Mod         , 1674733388494> 12,675,614> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/fr/tooltip_fr.txt
LOG  : Mod         , 1674733388494> 12,675,614> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/fr/ig_ui_fr.txt
LOG  : Mod         , 1674733388494> 12,675,614> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/fr/sandbox_fr.txt
LOG  : Mod         , 1674733388494> 12,675,614> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/fr/contextmenu_fr.txt
LOG  : Mod         , 1674733388494> 12,675,614> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/fr/recipes_fr.txt
LOG  : Mod         , 1674733388494> 12,675,614> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/en/recipes_en.txt
LOG  : Mod         , 1674733388494> 12,675,614> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/en/tooltip_en.txt
LOG  : Mod         , 1674733388494> 12,675,614> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/en/contextmenu_en.txt
LOG  : Mod         , 1674733388494> 12,675,614> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/en/sandbox_en.txt
LOG  : Mod         , 1674733388494> 12,675,614> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/en/itemname_en.txt
LOG  : Mod         , 1674733388494> 12,675,614> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/en/dynamicradio_en.txt
LOG  : Mod         , 1674733388494> 12,675,614> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/en/ui_en.txt
LOG  : Mod         , 1674733388494> 12,675,614> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/en/ig_ui_en.txt
LOG  : Mod         , 1674733388494> 12,675,614> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/cn/tooltip_cn.txt
LOG  : Mod         , 1674733388494> 12,675,614> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/cn/dynamicradio_cn.txt
LOG  : Mod         , 1674733388494> 12,675,614> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/cn/sandbox_cn.txt
LOG  : Mod         , 1674733388494> 12,675,614> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/cn/ig_ui_cn.txt
LOG  : Mod         , 1674733388495> 12,675,615> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/cn/items_cn.txt
LOG  : Mod         , 1674733388495> 12,675,615> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/cn/recipes_cn.txt
LOG  : Mod         , 1674733388495> 12,675,615> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/cn/contextmenu_cn.txt
LOG  : Mod         , 1674733388495> 12,675,615> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/es/dynamicradio_es.txt
LOG  : Mod         , 1674733388495> 12,675,615> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/es/recipes_es.txt
LOG  : Mod         , 1674733388495> 12,675,615> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/es/ig_ui_es.txt
LOG  : Mod         , 1674733388495> 12,675,615> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/es/items_es.txt
LOG  : Mod         , 1674733388495> 12,675,615> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/ru/tooltip_ru.txt
LOG  : Mod         , 1674733388495> 12,675,615> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/ru/itemname_ru.txt
LOG  : Mod         , 1674733388495> 12,675,615> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/ru/sandbox_ru.txt
LOG  : Mod         , 1674733388495> 12,675,615> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/ru/recipes_ru.txt
LOG  : Mod         , 1674733388495> 12,675,615> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/ru/dynamicradio_ru.txt
LOG  : Mod         , 1674733388495> 12,675,615> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/ru/contextmenu_ru.txt
LOG  : Mod         , 1674733388495> 12,675,615> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/ru/ig_ui_ru.txt
LOG  : Mod         , 1674733388495> 12,675,615> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/ptbr/dynamicradio_ptbr.txt
LOG  : Mod         , 1674733388495> 12,675,615> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/ptbr/recipes_ptbr.txt
LOG  : Mod         , 1674733388495> 12,675,615> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/ptbr/items_ptbr.txt
LOG  : Mod         , 1674733388495> 12,675,615> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/ptbr/ig_ui_ptbr.txt
LOG  : Mod         , 1674733388496> 12,675,615> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/ptbr/contextmenu_ptbr.txt
LOG  : Mod         , 1674733388496> 12,675,616> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/ptbr/sandbox_ptbr.txt
LOG  : Mod         , 1674733388496> 12,675,616> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/ptbr/tooltip_ptbr.txt
LOG  : Mod         , 1674733388496> 12,675,616> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/pl/dynamicradio_pl.txt
LOG  : Mod         , 1674733388496> 12,675,616> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/pl/ig_ui_pl.txt
LOG  : Mod         , 1674733388496> 12,675,616> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/pl/sandbox_pl.txt
LOG  : Mod         , 1674733388496> 12,675,616> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/pl/contextmenu_pl.txt
LOG  : Mod         , 1674733388496> 12,675,616> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/pl/items_pl.txt
LOG  : Mod         , 1674733388496> 12,675,616> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/pl/tooltip_pl.txt
LOG  : Mod         , 1674733388496> 12,675,616> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/pl/recipes_pl.txt
LOG  : Mod         , 1674733388496> 12,675,616> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/tr/dynamicradio_tr.txt
LOG  : Mod         , 1674733388496> 12,675,616> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/tr/tooltip_tr.txt
LOG  : Mod         , 1674733388496> 12,675,616> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/tr/ig_ui_tr.txt
LOG  : Mod         , 1674733388496> 12,675,616> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/tr/recipes_tr.txt
LOG  : Mod         , 1674733388496> 12,675,616> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/tr/contextmenu_tr.txt
LOG  : Mod         , 1674733388496> 12,675,616> mod "ExpandedHelicopterEvents" overrides media/lua/shared/translate/tr/sandbox_tr.txt
LOG  : Mod         , 1674733388499> 12,675,619> mod "ExpandedHelicopterEvents" overrides media/sandbox-options.txt`

**Comment by ChuckTheSheep** [comment]
That's not really useful log information.

Not sure if the problem is still persisting, but depending on your sandbox settings you may have made the game 'start' passed the mod's scheduler. Highly depends on in-game start day.

**Comment by ChuckTheSheep** [comment]
#90 seems to cover the topic and have more information.
