### ISSUE TITLE
[Suggestion] Toggle to disable the helicopter indicator?

### ISSUE THREAD

**Issue by Fluffy89** [TEHE-Studios/ExpandedHelicopterEvents#108]
Did a little bit of testing with the mod and it's interesting so far, but I'm not a huge fan of the helicopter direction indicator and prefer the lore-friendly vanilla way of not having the indicator.

Is this possible currently, and if so how do I disable the directional indicator?

**Comment by ChuckTheSheep** [comment]
Not possible currently, but I'll add a sandbox option or in-game option to do so.

**Comment by ChuckTheSheep** [comment]
Oh I forgot there's an in-game option that should disable the markers.

**Comment by Fluffy89** [comment]
I'm assuming it should be showing in the EPE tab for sandbox options, but it doesn't seem to be. Where would this in-game option be, and is there a config option I can add to the config file?
[https://gyazo.com/c6a6658975c31dbdc05741c517880b19](url)

**Comment by ChuckTheSheep** [comment]
In the escape menu options during game. Admins/hosts/SP should have access to change it. It is not a sandbox option.

**Comment by Fluffy89** [comment]
Is there a specific way I have to go about disabling the 'event markers' option in the escape menu? It says it can only be accessed/changed by admins or the host, so on my dedicated server I gave myself admin perms, and unchecked it and anytime I relog the checkbox is re-checked agian..

**Comment by ChuckTheSheep** [comment]
There is an issue where the settings don't save, try finding the config file on your machine.

**Comment by Fluffy89** [comment]
I know where the config files are for my dedicated server, but if "Event Markers" isnt a sandbox option, which config would I have to modify to disable "Event Markers"?

There's only the servername.ini, servername_SandboxVars.ini and servername_spawnregions.ini, "See server options" when in-game also shows "See Server Options" but this seems to just be the servername.ini config and has no line referencing "Event Markers".

**Comment by ChuckTheSheep** [comment]
Should be found in the lua folder to your server.

**Comment by Fluffy89** [comment]
Raven Male=true,
Gabby Female=true,
Jade Male A=true,
Jade Male B=true,
Jade Male C=true,
FlyerChoppers=true,
Police=true,

This is what I've got in the config, assuming it's missing the line for EventMarkers, I'm guessing adding the line 'EventMarkers=false' would be what I need to do to have it save properly, or what is the name of the line I need to add?

**Comment by ChuckTheSheep** [comment]
`eventMarkersOn=false,`
