### ISSUE TITLE
Server Console

### ISSUE THREAD

**Issue by PointWolf-Dev** [TEHE-Studios/ExpandedHelicopterEvents#109]
**Describe the bug**
LOG : Lua , 1674724200401> 101,346,838> Loading: steamapps/workshop/content/108600/2458631365/mods/Expanded Helicopter Events/media/lua/shared/zDebugTests.lua
WARN : Lua , 1674724200402> 101,346,838> LuaManager$GlobalObject.require> require("zDebugPanel") failed
WARN : Lua , 1674724200402> 101,346,839> LuaManager$GlobalObject.require> require("ExpandedHelicopter00b_IsoRangeScan") failed
WARN : Lua , 1674724200402> 101,346,839> LuaManager$GlobalObject.require> require("ExpandedHelicopter01a_MainVariables") failed

**Comment by PointWolf-Dev** [comment]
This error appears on loading up the server - Even a fresh server i get the same console errors

**Comment by ChuckTheSheep** [comment]
Require failing occurs sometimes, it appears to be a vanilla issue - but even when it does fail to require for the most part nothing breaks.
