### ISSUE TITLE
[Suggestion] Compatibility with "MRE XIII (1993) - Meal Ready to Eat MOD" by Alec

### ISSUE THREAD

**Issue by Galetaer** [TEHE-Studios/ExpandedHelicopterEvents#110]
As the title suggests, I would like to request integration with the "MRE XII (1993)" mod by Alec on the Steam workshop (please), to act as an optional replacement for the MRE's dropped by one of the military helicopter events

This request is only for the sake of immersion and fun-factor, as the MRE's in his mod are a bit more in-depth for turbo-nerds such as myself that like more clicking and inventory clutter... and minor amounts of cooking xp. 🤓

Thank you for your time, and if the idea is a bust or not in your realm of interest, no worries at all! 😎

**Comment by ChuckTheSheep** [comment]
Mod compatibility is not the priority at this very moment but can be visited in the near future.

See: https://github.com/TEHE-Studios/ExpandedHelicopterEvents/issues/103
