### ISSUE TITLE
Unable to exit News Helicopter

### ISSUE THREAD

**Issue by Tahvohck** [TEHE-Studios/ExpandedHelicopterEvents#111]
**Describe the bug**
Once entering a crashed WBLN news helicopter, I am unable to exit, even though the area is cleared out.

**To Reproduce**
Unknown: happens every time I try to exit this crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/1668722/215871706-41444d31-e814-4252-86ff-7f43dc32a69f.png)
![image](https://user-images.githubusercontent.com/1668722/215871783-86cfa146-6cef-4ef0-a3dd-7c6218071a6e.png)

**Console logs:**
[server-console.txt](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/files/10550563/server-console.txt)

**Comment by WadeWillequer** [comment]
I actually just had this issue today and was wondering about that too, got in the helicopter and was completely unable to exit, no error showed up on screen, doors were unlocked and even windows busted when zombies broke in and ate me alive

**Comment by ChuckTheSheep** [comment]
This issue may be resolved with the newest update - I have a feeling the vehicle is tilting ever so slightly to make the exits 'out of reach' in game.
