### ISSUE TITLE
Vanilla Helicopter event still occuring when heli event frequency in Sadistic AI Director is set to 'Never'

### ISSUE THREAD

**Issue by Fluffy89** [TEHE-Studios/ExpandedHelicopterEvents#113]
**Describe the bug**
The vanilla helicopter is set to Never occur as the mod says it overrides the mod and forces the vanilla event to not occur.

**To Reproduce**
Seemingly it happens in conjunction with EPE events, as the other night when  I was playing a jet flew by, a day before that a raider flew by, but today the vanilla event happened which is odd.

**Expected behavior**
Only the modded events from EPE should be occuring, since the vanilla helicopter is set to never occur.

[03-02-23_23-17-00_DebugLog.txt](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/files/10607880/03-02-23_23-17-00_DebugLog.txt)

**Comment by Fluffy89** [comment]
Forgot to add, but this is happening on a dedicated zomboid server.

**Comment by ChuckTheSheep** [comment]
#83 Potential fix is in the works for the next update.
