### ISSUE TITLE
Raider Chopper Music list

### ISSUE THREAD

**Issue by SummerDoge** [TEHE-Studios/ExpandedHelicopterEvents#114]
After having the Raider Chopper Event happen to me, I found out that the music is different each time.

Having a list of all possible songs would be good to be able to listen to the songs or just to find the names.

If you do make a list, it would be nice if it could be easily found somewhere, like this GitHub or even a link to the songs on the Mod page.

**Comment by ChuckTheSheep** [comment]
This folder contains the sounds used: [music](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/tree/main/Contents/mods/Expanded%20Helicopter%20Events/media/sound/music)

All sounds for the base mod is free-to-use.
