### ISSUE TITLE
Expanded Helicopter Events audio bug

### ISSUE THREAD

**Issue by StormySorcerer** [TEHE-Studios/ExpandedHelicopterEvents#115]
**Describe the bug**
After any of the helicopter events occur, the audio is glitched and will remain until the entire server is restarted.

**To Reproduce**
Have an event occur? There is a possibility that it could be conflicting with one of the other mods we have on the server.

**Expected behavior**
This didn't happen until the game updated a few times -- before the mod was working perfectly fine. After an event the sounds would go away and only return if another event happened. 

**Screenshots**
N/A.

**Console logs:**
Including with the report.
[coop-console.txt](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/files/10693535/coop-console.txt)

**Additional context**
Thank you so much for taking the time to read this -- my friends and I thoroughly enjoy this mod and hope there's a solution for this issue going forward!!

**Comment by sharkster91** [comment]
We are on a verge of finally fixing this with the next update. Thank you
for taking the time to post concisely- it helps a lot.

**Comment by ChuckTheSheep** [comment]
#85 - refer to this thread for more information. Thank you.
