### ISSUE TITLE
Mod not Available?

### ISSUE THREAD

**Issue by scraaq** [TEHE-Studios/ExpandedHelicopterEvents#117]
![Screenshot 2023-02-19 113740](https://user-images.githubusercontent.com/125780489/219914550-9c7a2753-a69b-409b-8864-cc0bfa54caa7.png)

**Comment by ChuckTheSheep** [comment]
Not sure what menu this is.

**Comment by scraaq** [comment]
> Not sure what menu this is.

Erm, So I got the Menu bottom right of the screen when I press ESC to check for MODS. I'll provide screenshot hold on.

**Comment by scraaq** [comment]
Alright found the Issue, I did not install Easy Config chucked making the mod not available.

**Comment by ChuckTheSheep** [comment]
Sounds good, and yes that's a required mod as stated in the workshop. 👍
