### ISSUE TITLE
Can't open Airdrop

### ISSUE THREAD

**Issue by Schmitti80** [TEHE-Studios/ExpandedHelicopterEvents#118]
**Describe the bug**

Hi there
I have had a Airdrop near me place. After i found it i see some "Quarantine Flyer" and 2 Boxes on a palette.
When i rightclick to the palette i can choose "Car Mechanic" (KFZ-Mechanik in German) but the progress bar just runs very fast, again and again and at the bottom right comes a red "Error" that counts, startet with 1 and +1 with every try.
I hope i explain it correctly, sorry for my english.

Of course i have several more Mods:
'83 AM General M923 Hillbilly
'92 AM General M998 + M101A3 Trailer
Arsenal(26) GunFighter
Arsenal(26) GunFighter [Felicity]
Brita's Armor Pack
Brita's Weapon Pack
Capacity vest and ammo straps
Common Sense
Easy Config Chucked
Eggon's Fanny Pack Balancing
Imp's Immunity
Lamborghini Diablo
Mod Options
Out of the Window
Refillable Lighters
Reorder Containers
Reorder the Hotbar
Smoker
Spawn items and clothing by occupation
Weapon Condition Indicator [41.60+]
You are infected Traid

**To Reproduce**

Just try it again and again, the Error comes every time.

**Expected behavior**

**Screenshots**

![20230220065940_1](https://user-images.githubusercontent.com/125853578/220023364-c702c9ec-4673-43b3-89db-e6488b0576f0.jpg)

**Console logs:**
Console logs are stored in your local files. `OS:\Users\<username>\Zomboid\console.txt`
For single player (or connected players) the file is named `console.txt`, for hosts or servers the file will be named `coop-console` or `server-console`. *Include any relevant logs - do not cut or edit the log to make it smaller.*

[console.txt](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/files/10780129/console.txt)

**Additional context**

**Comment by ChuckTheSheep** [comment]
What action are you performing shown in the screenshot?

**Comment by Schmitti80** [comment]
Ok, i will try it when i find my next drop. Had to start a new game. Thanks for making mods, much better than vanila.

**Comment by Schmitti80** [comment]
I write again if it doesnt work
