### ISSUE TITLE
AttackOnTarget error

### ISSUE THREAD

**Issue by kekikcilerakin** [TEHE-Studios/ExpandedHelicopterEvents#121]
**Describe the bug**
Error when heli shoots at us.

**To Reproduce**
Have heli shoot at you

**Console logs:**
`attempted index: getHealth of non-table: null function: heliEventAttackHitOnIsoGameCharacter -- file: ExpandedHelicopter04b_AttackOnTarget.lua line # 55 | MOD: Expanded Helicopter Events function: onServerCommand -- file: ExpandedHelicopter12b_OnServerToClientCommands.lua line # 216 | MOD: Expanded Helicopter Events java.lang.RuntimeException: attempted index: getHealth of non-table: null     at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)     at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:641)     at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)     at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)     at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)     at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)     at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)     at zombie.Lua.Event.trigger(Event.java:64)     at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:173)     at zombie.network.GameClient.receiveClientCommand(GameClient.java:1513)     at zombie.network.PacketTypes$PacketType.onMainLoopHandlePacketInternal(PacketTypes.java:1028)     at zombie.network.GameClient.mainLoopHandlePacketInternal(GameClient.java:644)     at zombie.network.GameClient.mainLoopDealWithNetData(GameClient.java:621)     at zombie.network.GameClient.update(GameClient.java:431)     at zombie.GameWindow.logic(GameWindow.java:232)     at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)     at zombie.GameWindow.frameStep(GameWindow.java:765)     at zombie.GameWindow.run_ez(GameWindow.java:681)     at zombie.GameWindow.mainThread(GameWindow.java:495)     at java.base/java.lang.Thread.run(Unknown Source) `

**Comment by ZoonTronGG** [comment]
not fixed
