### ISSUE TITLE
Empty FEMA drops and Helicopter Crashed bugged  in MP since most recent update

### ISSUE THREAD

**Issue by Nerdgamerdave** [TEHE-Studios/ExpandedHelicopterEvents#126]
Mod works as intended in Single Player.  But on the server I host (via paid server rental), EHE has multiple things not working since the most recent update (the update that includes the color coding of icons and the attack chopper).

FEMA Drops:
FEMA drops are empty for 9/10 drops.  
Myself and my players noticed that when a FEMA event launches, if it is color coded as green, then the drop works as intended and we will find 5, 10, or even 15 boxes inside the crate.

But 9/10 times, the helicopter icon shows up as solid white. as well as the parachute icon leading to the actual loot drop.  For all of these the crate is empty.

Players and myself noticed the solid white icon, rather than it turning green being associated with all the drops that turn up empty.

Replicated issue.
I replicated this several times by spawning a FEMA drop in a remote corner of the map and I got one drop to work (it was green), and the other 8 that I spawned all had empty crates (white icon not green).

Heli CRASHES:

A heli crashed on the Rosewood Gas Station prior to the latest update, which was a police chopper.  Worked as intended and expected.

After the update, the helicopter vanished and was replaced by a rectangular section of flooring made of dark wood.  Looks like about 10 x 8, as if someone used carpentry in the area to lay down the foundation to a house.

2 more crashes have occurred since then, and my players have reported the same.  They hear the helicopter, they hear loud gunfire and crashing sounds.

But when approaching the area, the spot on the ground has been replaced by wooden flooring rather than the police or military helicopter.

Replicated issue:
I replicated this twice so far.  Each copter crash creating a large rectangular patch of flooring that replaces whatever tree's, fencing, brush or terrain where the copter should have crashed.

Myself and every player has un-subscribed from the mod then re-subscribed, but these issues have persisted over the last 3 days.

**Comment by ChuckTheSheep** [comment]
Someone else has reported the wooden flooring thing as stemming from crashes. Honestly not sure what to make of that.

This mod doesn't modify the ground in anyway. 

That being said I'll have to retest the loot drops - the color coding being white may help figure out what's going on.

**Comment by ChuckTheSheep** [comment]
Since there is two seperate threads also reporting these issues, I'll defer to those to clean up the issue list.

#165 - Crashes/Wood Terrain Mystery
#104 - FEMA/Loot Drops being empty
