### ISSUE TITLE
Event sounds persist after event finishes. (Multiplayer)

### ISSUE THREAD

**Issue by RadioactiveJelly** [TEHE-Studios/ExpandedHelicopterEvents#128]
**Describe the bug**
Event sounds keep playing even after the event has finished. Encountered this with helicopters, jets and the air siren. Restarting the world fixes the issue. When the event is over for events like the helicopter or jets, it sounds like the sound is coming from the upper right no matter where you are in the world.

Edit: We are not on a dedicated server, just hosting a world through Steam.

**To Reproduce**
Wait for event to trigger, observe sounds persisting well after the relevant event has supposedly finished.

**Expected behavior**
Event sounds should stop when event ends.

**Console logs:**

[coop-console.txt](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/files/10866932/coop-console.txt)

**Additional context**
Other Mods Installed:
- Vanilla Firearms Expansion (B41)
- Fluffy Hair
- Mod Options (B41)
- Tsar's Common Library
- Mod Manager (Server)
- Backpack Borders
- Improved Hair Menu
- An Exhilaratingly Organized Literature Mod
- Has Been Read
- RV Interior
- Better Flashlights
- Spongie's Hair
- Become Brave
- Become Desensitized
- Material Weight Reduction 20%
- Item Tweaker API
- Undead Survivor
- True Actions. Act 3 - Dancing
- Rain Wash
- Basements
- Canteens and Bottles
- Swap It
- Easy Config Chucked
- Boredom Tweaks
- Clear Description for Moodles
- Snow is Water
- Spongie's Clothing
- They Knew
- True Actions Act 1 and 2 - Sitting and Lying
- Weapon Condition Indicator
- Mod Manager
- More Description for Traits
- Better Sorting
- Common Sense

**Comment by JamesLlance** [comment]
I have the exact same problem, does anyone know?

**Comment by ChuckTheSheep** [comment]
#85 Duplicate
