### ISSUE TITLE
Option for keeping airdrops marked at least for a few hours?

### ISSUE THREAD

**Issue by KillerTheFlareon** [TEHE-Studios/ExpandedHelicopterEvents#135]
Title, I could've sworn this was a thing before, but eh, memory's not great.
Anyway, I find it particularly difficult to find airdrops--and honestly have more of a chance of just stumbling onto one than when I look for it. Haven't been able to find any since the update that makes them disappear so fast.
Even in games, for an example like rust, where you can visually see and roughly estimate where the airdrop is more often than not I end up losing the thing entirely.

So myself and i'm sure other people would appreciate some kinda option to keep the airdrop marked on your screen with a directional indicator for a few in-game hours to find the damn thing..

**Comment by Nerdgamerdave** [comment]
place a marker on your map to tag for searching later may help.

The arrow points in the direction of the drop.  If the pointer is super long, it's at the end of your visual range (about 200 tiles).

If it's medium size, it's withing about 1 block away.  super short, means you are within just a few tiles of it.

It's super reliable to just drop a map marker down in the rough direction.

flyers are also scattered all over the ground nearby a drop, along with flyers along the path the helicopter flew.  Like breadcrumbs, they lead you to the supply drop

**Comment by KillerTheFlareon** [comment]
Oh. I always thought that the airdrop was in some distant location since I could never really find/see it.
Good to know, though I still think having an option for it would be nice.

**Comment by ChuckTheSheep** [comment]
Drops will have flares in the future as well - so there will be a sound component to it. Also, markers will last a bit longer. I'll think about adding a sandbox option for marker length.
