### ISSUE TITLE
Cmd flood and inactive events

### ISSUE THREAD

**Issue by Kolbaszharcos** [TEHE-Studios/ExpandedHelicopterEvents#143]
**Describe the bug**
Error message flooding server cmd
helicopter not appearing and no future events happening

**To Reproduce**
Unknown

**Expected behavior**
Helicopter roaming around trying to hunt us down >:D

**Screenshots**
![image](https://user-images.githubusercontent.com/18143645/226172620-1019650e-704a-43ec-a188-428146f4c773.png)

**Console logs:**
Cannot provide at this time , can do if needed later.

**Additional context**
Havent seen any activity while happening

**Comment by Kolbaszharcos** [comment]
Server restarted, helicopter spawned in after restart , killed a zombie then returned to base

**Comment by Kolbaszharcos** [comment]
Happened again with the same event, only a server restart fixed it

**Comment by ChuckTheSheep** [comment]
The event should auto cutoff after a while. I will look into why it's having trouble finding a target.

**Comment by Kolbaszharcos** [comment]
Yesterday we had another, same issue. All of us are disconnected then with the server the event paused. After one player connected, the event started flooding without changes, even with one player.

**Comment by gonenoculer5** [comment]
Can confirm I'm getting this on my server aswell. https://i.imgur.com/1AhQDpN.png

**Comment by gonenoculer5** [comment]
Could have something to do with this which is spamming now and then alongside it. https://i.imgur.com/v1FfZQs.png

**Comment by gonenoculer5** [comment]
Interestingly enough it seems that after the player it was trying to path to disconnected, it stopped blowing up the log. Could be an issue with the helo trying to path properly. https://i.imgur.com/HmjOS4Z.png

**Comment by ChuckTheSheep** [comment]
I appreciate the screenshots but you're cutting off information to identify the errors source. 😅

**Comment by gonenoculer5** [comment]
Sure, probably should have just dropped the console log from the getgo, lemmie grab a pastebin for you.

**Comment by gonenoculer5** [comment]
The file is unironically too large to pastebin due to the log spam, bare with me.

**Comment by ChuckTheSheep** [comment]
This should be fixed for next patch.
