### ISSUE TITLE
Recycle Destroyed Rotor blades

### ISSUE THREAD

**Issue by raider7799** [TEHE-Studios/ExpandedHelicopterEvents#158]
Submit an idea 

 Disassemble Mangled Rotor Blades around crash site , i saw it lying ariund and it cant be destroy + too heavy to put in a trash bin
 
 so why dont scrap it for some sheet metal or scrap metal !!!!

**Comment by ChuckTheSheep** [comment]
You should be able to cut it down using a propane torch.
