### ISSUE TITLE
Main Menu UI Disappearing

### ISSUE THREAD

**Issue by TheRealLeoner** [TEHE-Studios/ExpandedHelicopterEvents#162]
**Describe the bug**
Upon enabling the mod and going back into the main menu the whole main menu UI disappears.

**To Reproduce**
Enable the mod and going back to the main menu.

**Expected behavior**
I expected the main menu UI to be there for me to play the game.

**Screenshots**
![image_2023-04-13_130202154](https://user-images.githubusercontent.com/130368128/231739304-a6f73a8a-87f6-4512-a93b-7907c52e5c8c.png)

**Console logs:** 
[console.txt](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/files/11221350/console.txt)

**Additional context**
I have the required mods installed and enabled.

**Comment by sharkster91** [comment]
Doesn't look like our issue, you are having a substantial amount of errors
from Autotsar's.

**Comment by ChuckTheSheep** [comment]
I would suggest reverifying your cache / deleting the install directories for the EasyConfigChucked mod and reinstalling it.

Your error:
> Callframe at: upper
> function: create -- file: EasyConfig_Chucked0_Menu.lua line # 235 | MOD: Easy Config Chucked

Upper() is not called on line # 235 -- So my best guess would be you have old files that Steam is not able to remove.

**Comment by ChuckTheSheep** [comment]
Stale.
