### ISSUE TITLE
Adding on MP rented server shows not available

### ISSUE THREAD

**Issue by shoompaps** [TEHE-Studios/ExpandedHelicopterEvents#163]
Hello. I've added both the mod name and workshop id to my rented server. Also added the preset under the sandbox lua file as instructed. However, when I start the server, it deletes the preset in the sandbox lua. Any help?

**Comment by impvhc** [comment]
I had the same problem, this mod has a dependency that you need to install  EasyConfigChucked
https://steamcommunity.com/sharedfiles/filedetails/comments/2529746725
