### ISSUE TITLE
Exception thrown java.lang.IllegalStateException at UIManager.update line:685

### ISSUE THREAD

**Issue by shadowhunter100** [TEHE-Studios/ExpandedHelicopterEvents#170]
**Describe the bug**
UI Manager is reporting an error...

"ERROR: General     , 1683136409143> ExceptionLogger.logException> Exception thrown java.lang.IllegalStateException at UIManager.update line:685."

**To Reproduce**
I'm running a local mod that is also interacts with the main menu options... so I think there is a possible conflict, but I want to confirm if anyone else has the same issue.

**Expected behavior**
I expected no errors to appear in the game nor an error being logged to the console.

**Screenshots**

**Console logs:**
![image](https://user-images.githubusercontent.com/131904770/236009660-6d43c3e3-7825-4895-935a-882e29e9076e.png)

**Additional context**
I am currently working to update an abandoned mod for my own use until I get permission to distribute it.

The original code was quite a mess to say the least... and I'm also new to Lua, so I expect a lot of issues.

Here is the github repo to the my mod, (I also need to stop committing directly to the main branch...)
https://github.com/shadowhunter100/SuperbSurvivorsContinued/tree/main/mods/SuperbSurvivorsContinued

**Comment by ChuckTheSheep** [comment]
I'm not sure if this mod is related to thak issue. Also as far as I'm aware superb survivors is still being worked on.

**Comment by shadowhunter100** [comment]
Yeah, the error only shows up when I have Superb Survivors loaded, (both the steam workshop one and my fork).

I've left a few messages for nolanritchie, but I haven't gotten a response from him at all.

The steam workshop item has been broken for about 3 months now hence I was looking at updating it myself.

**Comment by shadowhunter100** [comment]
Yeah, that is what I'm guessing at right now; I'll probably rewrite the entire options/config later as SS doesn't have sandbox options right now.
