### ISSUE TITLE
What are the names like Raider etc

### ISSUE THREAD

**Issue by Taslonih** [TEHE-Studios/ExpandedHelicopterEvents#174]
I would like to disable the helicopters that shoot at us, what are the names in the list please

ExpandedHeli = {
        -- Minimum=0 Maximum=999 Default=0
        StartDay = 0,
        -- Minimum=1 Maximum=999 Default=90
        SchedulerDuration = 90,
        ContinueScheduling = false,
        ContinueSchedulingLateGameOnly = true,
        Frequency_jet = 6,
        Frequency_police = 6,
        Frequency_news_chopper = 6,
        Frequency_military = 6,
        Frequency_FEMA_drop = 1,
        Frequency_samaritan_drop = 1,
        Frequency_survivor_heli = 6,
        Frequency_raiders = 1,

**Comment by ChuckTheSheep** [comment]
https://github.com/TEHE-Studios/ExpandedHelicopterEvents/blob/main/docs/FEATURES.md
