### ISSUE TITLE
The mod broke all my Pc (send help)

### ISSUE THREAD

**Issue by 4RTHUX** [TEHE-Studios/ExpandedHelicopterEvents#175]
**Describe the bug**

Ok, when i downloaded the mod for the first time, nothing happenend, the problem started about 2 weeks after that. All the time when i open the game the EHE is on my game, all servers, all saves, i uninstalled the game, unsub from workshop, and even deleted all zomboid files (Users/Steam) still not working at all, the mod keeps going back. no, the mod is not Subscribed, and yes, it keeps going back to my game, now, all the time i host a server i get about 1000000 (Literally) Errors and in about 2 days or so the server get corrupted.

**To Reproduce**
it Happens all the time LOL

**Expected behavior**
I don't Need to talk about that.

**Screenshots**
[https://cdn.discordapp.com/attachments/1098705850782199818/1107802125616037888/image.png](url)
[
![image](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/assets/133716595/e345b011-ac25-4443-b74a-f6812e9df444)
](url)

Please help me :( 
[console.txt](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/files/11482483/console.txt)
[coop-console.txt](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/files/11482484/coop-console.txt)

**Comment by ChuckTheSheep** [comment]
I would need a more clear report of events.
The logs have no errors other than one for sleeping bags.

Your screenshot shows a few mods in steam enabled, and your second image are the tabs in options.

Please post the log files after the '1000000' errors occur.
