### ISSUE TITLE
Event sound still going after the event passes on  private multiplayer server

### ISSUE THREAD

**Issue by ThisArgon** [TEHE-Studios/ExpandedHelicopterEvents#177]
**Describe the bug**
Event sound (like helicopter) still playing even after 10 or more minutes

**To Reproduce**
Steps to reproduce the behavior: No idea how does it happen

**Expected behavior**
We expected the event to stop after 10 minutes of it happening but it was still going on

**Comment by southpaw43** [comment]
same issue, helicopter won't stop spinning in the air, and the siren of a nuke I think? it won't stop we been playing 6hrs and it still keep going, its been a part project zomboid world and it's frustrating to hear it

**Comment by Maxoxpower** [comment]
same error... private servor we all hear the same sounds after an event.!  hope you can fix this cause i love this mod so much! :O 

must disable for now this is annoying :(

**Comment by ChuckTheSheep** [comment]
#85
