### ISSUE TITLE
Ac-130 Gunship

### ISSUE THREAD

**Issue by SugarBaguetto** [TEHE-Studios/ExpandedHelicopterEvents#179]
So a quick suggestion is to add a AC-130 gunship for early days only where the military is trying to kill zombies on key installations. A example is that the  Gunship will spawn on the first days near survivors while it is trying to help you by shooting zombies near your location you will hear a loud noise attrackting more zombies but it will use its Howitzer to kill zombies wich are far away from you and its 30mm and minigun to kill zombies near you. It will only spawn once and with it a lot of zombies will spawn too. The Howitzer does destroy buildings so you would have to be in the open so it doesnt destroy your building you are inside of.

**Comment by sharkster91** [comment]
No.
