### ISSUE TITLE
file doesnt match the one of the server 

### ISSUE THREAD

**Issue by Maxoxpower** [TEHE-Studios/ExpandedHelicopterEvents#180]
**Describe the bug**
friend cant enter server cause of the mod

**To Reproduce**
get the mod installed ( beta version)

**Expected behavior**
working

**Screenshots**
![ERROR HELICOPTER](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/assets/26907483/f6abc28a-eb4d-464d-81c7-e69bea30cf90)

dont have console log its my friend who dont know the game who send me this..he sub to the beta version and cannot enter but we got the same modlist

**Comment by ChuckTheSheep** [comment]
Make sure you and your friend are also not subscribed to the main mod.
