### ISSUE TITLE
Events unable to find targets (needs verification of an issue)

### ISSUE THREAD

**Issue by Paz0s** [TEHE-Studios/ExpandedHelicopterEvents#184]
**Describe the bug**
Several repeated messages that do not stop, the event does not occur in the game with anyone. 18 players online when I realized.

Server has 64GB RAM, CPU RYZEN 5 5600x

**To Reproduce**
Dont know

**Expected behavior**
Appear only verbose in cmd

**Screenshots**
https://i.imgur.com/d1sR6Ac.png

**Console logs:**
https://pastebin.com/Bf7aeMaH
The original file has 160mb size

**Additional context**
I woke up and cmd was flooding endlessly.

**Comment by sharkster91** [comment]
CMD flooding isn't specifically an issue. I can see that the helicopter
lost targeting and we are aware of it.

Thanks.
