### ISSUE TITLE
Expanded Helicopter Events: Stuck Sounds

### ISSUE THREAD

**Issue by AlyssaFaden** [TEHE-Studios/ExpandedHelicopterEvents#185]
**Describe the bug**
Multiplayer game - hosted on players computers, 2 players
Howdedodee time (?) helicopter appeared, flew over head (we were hiding), then seeme dto loop back overhead and from that point forweard the sound of its rotors and the "howdee doodee time" music kept playing on a constant loop. Unfamiliar with the event, we went to check it out and theree days later of this going on and the sounds looping, we positioned ourselves 'under it' ... pretty sure we pinpointed where on the map it was coming from, but there was no helicopter there, no shadow, just looping sounds. We logged out of game several days later ... and the sounds were still looping.

**To Reproduce**
Start multiplayer co-op hosted game and wait for event to appear?

**Expected behavior**
I would expect the sound loop to stop when the event is over

**Screenshots**
none available

**Console logs:**
[console.txt](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/files/11724791/console.txt)

**Additional context**
N/A

**Comment by Chuckleberry-Finn** [comment]
See: #85
