### ISSUE TITLE
I installed this in an old singleplayer save, I made a backup and tested it, it worked, now in my original save it doesn't seem to be working

### ISSUE THREAD

**Issue by Daniel-2609** [TEHE-Studios/ExpandedHelicopterEvents#188]
I used the "Change Sandbox Options" mod to configure it and I made the events be very frequent to see if it worked, it did, after a while I got a jet or something, anyway it worked, but, It has been 2 weeks (IRL) since I have been playing in my original save, I only have raiders and military on, respectively in uncommon and in rare, I have been playing for those 2 weeks, lots of hours, an I still don't get any event, I checked everything, I don't know what it is. Can somebody help me? I don't know what is happening.

**Comment by Chuckleberry-Finn** [comment]
Events stop coming after a set amount of time, unless you also adjust those accordingly adding the mod to an existing save may not yield events. In the future provide a console.txt in order to better check what's going on.
