### ISSUE TITLE
Helicopters bullets dont hit players at all

### ISSUE THREAD

**Issue by QuailingAround** [TEHE-Studios/ExpandedHelicopterEvents#190]
**Describe the bug**
When a helicopter fires at a player, it does nothing to the person whos being shot at

**To Reproduce**
 Let a hostile helicopter shoot you

**Expected behavior**
Do actual damage to the player instead of doing nothing.

**Screenshots**
Sadly i dont have any screen shots.

**Console logs:**
[Sadly i had to cut it because it was so god dam big for me to upload] https://pastebin.com/SvHVki2h
**Additional context**

**Comment by sharkster91** [comment]
This is because you have encountered a bandit helicopter that isnt shooting
directly at you. I'll likely change this so they just nail you instead.
