### ISSUE TITLE
[Suggestion] Make helicopters crash using Stinger Missiles

### ISSUE THREAD

**Issue by Allahs3000BlackFighterJets** [TEHE-Studios/ExpandedHelicopterEvents#191]
One of the biggest problems that I've encountered is being attacked by helicopters while out in the open, let's say driving down a highway with no building nearby or walking out in a field. I've seen the roadmap page and noticed that shooting at helicopters was one of the "nice to have" features. I decided to think through and try to pseudocode what I think would be a better interim (not to mention easier to code and implement) solution to provide a player a rare and heavy "get out of jail free" card: Stinger missiles (OP note:  Or maybe a FIM-43 Redeye? considering you'd be getting these from the NG I'd expect them to have older stuff, but _everyone_ knows what a Stinger is, fewer what a Redeye is)

Stinger missiles would be very rare weapons that would be of one time use, the weapon itself being the Stinger (obviously), but also would require ammunition in the form of missile tubes (the Stinger itself is reusable but the missile tubes are not). Upon firing, the game would check if there was a helicopter in the player's chunk, if so, it would then cause the helicopter to crash, the details of which are given in the pseudocode which I've (hopefully) [ attached with this](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/files/11875583/shittyidea.txt) 

I would also like to note that It might be better from a balance perspective to make stingers single use only and merely replace a stinger on firing with a "used stinger" dummy weapon. This would emphasize it's intended role of a "get out of jail free card" and not as something to be used simply to down a helicopter to try and salvage supplies.

**Comment by sharkster91** [comment]
No, there are currently plans to add an MIM-104 in 2028 with the Alien
Invasion update.
