### ISSUE TITLE
Help with Creating a submod, Debug events, Helicopter Disguises and Music

### ISSUE THREAD

**Issue by CreaosisSquared** [TEHE-Studios/ExpandedHelicopterEvents#195]
So I am currently trying to integrate EHE into a mod I am creating - and would like to add support for custom disguises against new types of helicopters (I am trying to add helicopters for the Commonwealth and Civic Republic from TWD, and would like wearing their uniforms to prevent them from targeting you). I saw this was possible with police and military things already existing in the code, but how do you define what items contribute to a faction disguise?

I am unfamiliar with all of this - my assumption is that the 'string' part of the code will look for a word in the clothing items' ID? Ie, setting the part in quotes to look for as "CRM" would identify the Civic Republic clothing from the CRM pack? Or is this wrong?

Additionally, I believe it was possible at some point for raiders or similar events to play music over loudspeakers to draw in zombies/taunt players when hostile - I have not played for months so don't know if that's still in - if so, how can I specify audio to be played and what events this is tied to?

Edit: Furthermore, after some working on the mod and attempting to implement my own map-based flyers it seems they are broken - not only mine refusing to spawn even with item spawner cheats (simply doesnt appear as a listing) it seems to be the same for the EHE's native flyers (Prevention, quarantine, etc). Were they removed? Is there an incompatible mod preventing map usage? Vanilla maps appear to be gone too.

Additionally, how can I add events I want to add to the debug menu in order to spawn them in for testing?

**Comment by Chuckleberry-Finn** [comment]
Working from simplest to answer to more difficult: Yes raiders/events can play music - that's handled in the presets file.

Also in the preset files are a parameter for presets called `hostilePredicate`, this is a function that determines if the thing in question should be attacked beyond what its `hostilePreference` is. In the case of `hostilePredicateCivilian` it checks for clothing being worn and compares a number of things to match against police or military. 

The events should be automatically registering in the debug menu if they're added properly to presets.

I'm not sure what you mean by flyers being missing.

**Comment by CreaosisSquared** [comment]
The flyers being missing after further investigation appears to be a bizarre, non-related bug causing all items based on the map item (including vanilla ones) to simply not be acknowledged as existing by my game, even under item spawning menus and such.
