### ISSUE TITLE
Sound bug is taking it comeback 

### ISSUE THREAD

**Issue by AstrayCuriosit** [TEHE-Studios/ExpandedHelicopterEvents#201]
I really hope someone is still updating and looking for this mod but currently me and my friends experiencing sound after any helicopter event that is stuck in place forever until you reload the server. Is there something that can be done?

**Comment by zayisawesomethe2nd** [comment]
Also having this issue on a multiplayer server hosted on my computer that my friends and I are playing on. So far this has occurred with an airdrop helicopter where the sound kept playing on the left, and a jet sound, which only one of my friends could hear. 

Is there any way that an admin could end the sounds using a command? It would save a lot of hassle.

**Comment by Chuckleberry-Finn** [comment]
#85
