### ISSUE TITLE
MRE dissapearing after dropped on the ground and left for few days?

### ISSUE THREAD

**Issue by JonnyJalapeno** [TEHE-Studios/ExpandedHelicopterEvents#212]
Hello.

I've opened packages with mre which were dropped from heli, placed the content on the ground, and to my unpleasant surprise after few days the mre dissapeared while sealed watter cans are still there. Is this WAD?

**Comment by Chuckleberry-Finn** [comment]
I'm not sure was is WAD. Are you playing solo?

**Comment by JonnyJalapeno** [comment]
Yeah solo, WAD means Works as Designed.

**Comment by Chuckleberry-Finn** [comment]
I don't know why they would disappear - as far as I know they don't rot.
