### ISSUE TITLE
Mod breaks when playing with RV interiors, requesting compatibility patch

### ISSUE THREAD

**Issue by blackpurge** [TEHE-Studios/ExpandedHelicopterEvents#214]
The RV interiors mod teleports you to another map when you enter your RV, and since this mod uses a heatmap of where you've been  to target the events, it more than likely will spawn the helicopter events on the RV map instead of the actual game map. I can think of a few ways to solve this but they would all probably need a mod specific patch. 

1) stop mapping the player when they've entered the RV map
2) count the time spent on the RV map as time spent where the RV currently is instead
3) (a more elaborate solution) add a feature where you can select/deselect where helicopter events are allowed to happen, so that we can tweak which maps can get what types of helicopter event

**Comment by sharkster91** [comment]
No.

**Comment by rosieposieeee** [comment]
I've had this problem as well.
