### ISSUE TITLE
Не запускается события с вертолетами

### ISSUE THREAD

**Issue by mrgestum** [TEHE-Studios/ExpandedHelicopterEvents#215]
**Describe the bug**
При создании игры в песочнице, с правкой " месяцев с начала апокалипсиса" у меня выбрано 12. Сколько раз не пробывал играть, событие Вертолетов не активно, ничего не происходит уже 2 месяца с начала игры, в то время когда Я создаю без правок на время, "месяцев с начала апокалипсиса, мод работает. Как исправить? 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Console logs:**
Console logs are stored in your local files. `OS:\Users\<username>\Zomboid\console.txt`
For single player (or connected players) the file is named `console.txt`, for hosts or servers the file will be named `coop-console` or `server-console`. *Include any relevant logs - do not cut or edit the log to make it smaller.*
[coop-console.txt](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/files/12268773/coop-console.txt)
[console.txt](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/files/12268774/console.txt)

**Additional context**

**Comment by Chuckleberry-Finn** [comment]
Not sure what you're asking or what bug you're reporting.

Looking at your console log:
`java.nio.file.NoSuchFileException: /lua/EasyConfigChuckedServerConfigs/Addicted_config`
`java.nio.file.NoSuchFileException: /lua/EasyConfigChuckedServerConfigs/GestumMods_config`
`java.nio.file.NoSuchFileException: /lua/EasyConfigChuckedServerConfigs/PZ1_config`

This is a vanilla issue, and if your game is locking up, you need to manually delete these files.

**Comment by mrgestum** [comment]
Это соло игра, а не сервер. Когда создаешь песочницу и ставишь к примеру 12 месяцев с начала апокалипсиса, дабы перемотать время уже на старте, сам мод не выдает ошибок, что очень хорошо, никаких притензий. Само событие пасивно и не стартует, к слову ничего не происходит((. Но когда не выбираешь режим спустя 12 месяцев, оставив его в дефолтном значении, тогда все работает. Просто мне нравится играть в мире где вся еда испорчета и присутствует сильная эрозия, проблема не глобальна, быть может и не стоит обращать внимание, но сообщить нужно.

**Comment by mrgestum** [comment]
This is a solo game, not a server. When you create a sandbox and set, for example, 12 months from the beginning of the apocalypse in order to rewind time already at the start, the mod itself does not give errors, which is very good, no pretensions. The event itself is passive and is not earned, by the way, nothing happens ((. But when you do not select the mode after 12 months, about transferring it to the default value, then everything works.

**Comment by mrgestum** [comment]
This is a solo game, not a server. When you create a sandbox and set, for example, 12 months from the beginning of the apocalypse in order to rewind time already at the start, the mod itself does not give errors, which is very good, no pretensions. The event itself is passive and does not start, by the way, nothing happens ((. But when you do not select the mode after 12 months, leaving it at the default value, then everything works. I just like to play in a world where all the food is spoiled and there is strong erosion, the problem not global, perhaps you should not pay attention, but you need to report.

**Comment by Chuckleberry-Finn** [comment]
The default scheduling system ends events on 90 days. The scheduler duration setting would stretch the scheduler to longer. If you want events forever instead you can toggle that on too. In your case you could also set the start day to after 12 months to possibly get all the events.

**Comment by mrgestum** [comment]
Большое человеческое спасибо, за подробности о которых я не мог знать, теперь я понял, что 90 дней это финал, я не копался в настройках мода. Просто есть пункты которые не переведены и что они значат увы не известно, наверно это оно и есть.

**Comment by Chuckleberry-Finn** [comment]
I had to google translate - but I'm glad the information helped. Check our the FAQ and Features pages on here for more information.

https://github.com/TEHE-Studios/ExpandedHelicopterEvents/blob/main/docs/FEATURES.md

https://github.com/TEHE-Studios/ExpandedHelicopterEvents/blob/main/docs/FAQ.md
