### ISSUE TITLE
ehe.flyer.txt

### ISSUE THREAD

**Issue by TheMuFFinM4n** [TEHE-Studios/ExpandedHelicopterEvents#220]
**Describe the bug**
Game only started with Easy Config & errorMinifer & Expanded Helicopter and still shows this error

![Unbenannt](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/assets/142125536/7a8dba96-7f66-4fe2-ae7f-07fbaaf567ab)

**Comment by sharkster91** [comment]
[Your issue is regarding your server missing required files, not an issue with the mod itself.](https://www.youtube.com/watch?v=fSfsWFUmaX8)

**Comment by TheMuFFinM4n** [comment]
What should i do then? I reinstalled the mod and that didn't help either. What else can I do?

**Comment by sharkster91** [comment]
I don't really host servers, however, if I were to look it'd be in the
actual core installation folder and deleting it as the workshop is
notorious for holding over files. Other than that, i'd check over at the
official Discord since there is stuff for server owners.
