### ISSUE TITLE
Eating an MRE throws an error, and is not replaced with a wrapper.

### ISSUE THREAD

**Issue by dimension128** [TEHE-Studios/ExpandedHelicopterEvents#221]
**Describe the bug**
The MRE item is not replaced with the MRE Wrapper, and a lua error is thrown.

**To Reproduce**
Select Eat -> All on an MRE

**Console logs:**
[15-08-23_02-08-52_DebugLog.txt](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/files/12341703/15-08-23_02-08-52_DebugLog.txt)
The error starts on line 6508

**Additional context**
I have been playing with friends for quite some time. Without intentionally changing anything with mods, this started occurring some time ago. I'm sorry I cannot be more specific, we play infrequently.

To test, I started a singleplayer save with only three mods active. 

- **EasyConfig Chucked** which the workshop says is required by EHE; 
- **errorMagnifier** which is recommended by EasyConfig Chucked;
- **Expanded Helicopter Events**.

I also unsubscribed and resubscribed to all three mods, to hopefully ensure clean up to date files.
I used sandbox mode to click the "Continue Scheduling Forever" option. This likely irrelevant, but I wanted to keep variables the same as my multiplayer game where possible.
In debug mode, I spawned an MRE, ate it, and this error still happens in the brand new save.
In debug mode I can see that the objects item type is, `EHE.MealReadytoEatEHE` and the wrapper is `EHE.MREWrapperEHE`
The error complains about not being able to find an item called `EHE.MREWrapper`
I don't know if this is the issue, or the debug log is truncating the string.

**Comment by dimension128** [comment]
Poking around I've found that changing line 64 in EHE_food.txt from:
```
		ReplaceOnUse = MREWrapper,
```
To;
```
		ReplaceOnUse = MREWrapperEHE,
```
Makes it work correctly in game.
Obviously manually changing the file isn't an ideal way to correct it for multiplayer. But I hope this is useful to whoever needs to see this.

**Comment by Chuckleberry-Finn** [comment]
Thank you for tracking that down.
