### ISSUE TITLE
TO MANY UPDATES BREAKING SERVERS

### ISSUE THREAD

**Issue by trilliam25** [TEHE-Studios/ExpandedHelicopterEvents#222]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Console logs:**
Console logs are stored in your local files. `OS:\Users\<username>\Zomboid\console.txt`
For single player (or connected players) the file is named `console.txt`, for hosts or servers the file will be named `coop-console` or `server-console`. *Include any relevant logs - do not cut or edit the log to make it smaller.*

**Additional context**

**Comment by sharkster91** [comment]
Damn, that's wild Will Livingston. However, after a long and thoughtful review of our policies- we will continue to update as often as we please.

**Comment by Chuckleberry-Finn** [comment]
Additionally, use UdderlyUptoDate or other tools to maintain your server. Ask your players/hosts to verify cache, etc.
