### ISSUE TITLE
Image and 3D model / Zombies Kill by the Heli bug

### ISSUE THREAD

**Issue by D4RkWaT3Rs** [TEHE-Studios/ExpandedHelicopterEvents#226]
Hello !

**Describe the bug**
The "Protein Bar" item has no image in the inventory, so we can't place it on the floor because the 3D model doesn't appear. Instead, a navy blue bubble with a cyan question mark appears.

When military helicopters engage a zombie and kill it, the zombie is left "naked" with no clothes on.  

**To Reproduce**
![image](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/assets/143303621/d6f7dbfa-5b17-4a22-9fa7-8ebc2adec53f)
![image](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/assets/143303621/161d019b-9b76-48ca-9daf-c2f6fa9d5dd7)

**Expected behavior**
I expected the image of the item in the inventory to be displayed and the 3D model to appear when I placed it on the surface.
Zombies aren't normally completely "naked" except for a zone event in the vanilla game, it would be normal for them not to be naked because of this "bug" unless it's normal and I'm not aware of it.

**Screenshots**
![image](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/assets/143303621/d6f7dbfa-5b17-4a22-9fa7-8ebc2adec53f)
![image](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/assets/143303621/161d019b-9b76-48ca-9daf-c2f6fa9d5dd7).
![image](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/assets/143303621/1ad82e9b-6664-4853-8a3a-a7854cf831b5)

**Console logs:**
![image](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/assets/143303621/e0fa2a64-0581-4bf9-a9e9-715c57755180)

**Additional context**
I only have the Expended Helicopter and Easy Config Chucked Mods active on my solo sandbox game in debug mod, no other items like the MRE have this problem.

**Comment by sharkster91** [comment]
It's a pulled item. I am going to finish the job next patch.
