### ISSUE TITLE
Problem with mod files

### ISSUE THREAD

**Issue by Smigolska** [TEHE-Studios/ExpandedHelicopterEvents#232]
**Describe the bug**
I was having problem with Expanded Helicopter Events mod and i deleted files manually. After unsubscribing and subscribing the mod, workshop don't want to download new files. its just show download bar and after few seconds its shows it has been downloaded but there is no amount of downloaded MB and mod its not showing in mod options in ingame menu. Its only shows itself in MP menu in "Steam Workshop" page but not in "Mod" page after adding it to the server.

**To Reproduce**
Exactly the same as in descritpion of the bug

**Expected behavior**
I was expecting that workshop will redownload files automaticly but it didn't.

**Screenshots**
![One](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/assets/144844452/fce20df2-9bbf-4979-947f-ce0c000bb072)
![Two](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/assets/144844452/7ef26c0f-a272-4691-9bcb-b21cdc6676b8)

**Console logs:**
No point of Console logs because there is no files to load from the mod.

**Additional context**
Before uninstalling the mod, it didn't want to load in multiplayer so i changed load order but it still didn't work (checked in Admin mode for items from the mod and tried to spawn helicopter in debug menu - no items or option to spawn)
It's not a problem with a mod, its workshops problem. But i can't find any solution to the problem.

**Comment by Chuckleberry-Finn** [comment]
Try reverifying your cache - also confirm you have the required mods installed.

**Comment by Chuckleberry-Finn** [comment]
👍
