### ISSUE TITLE
Attack Helicopters Fail to find target bug

### ISSUE THREAD

**Issue by Origichen** [TEHE-Studios/ExpandedHelicopterEvents#233]
**Describe the bug**
Any event that involves an attack helicopter, whether it be the police or raid helicopters, the console is spammed with a bunch of errors indicating that it's failing to find a target.

**To Reproduce**
I'm not sure how exactly to produce it but it seems to happen whenever an attack helicopter shows up.

**Expected behavior**
What should happen is the attack helicopter should spawn and shoot at what ever targets it's aiming at.

**Screenshots**
No screenshots, just logs.

**Console logs:**
LOG  : General     , 1694575396215> 635,666,713>  --- HELI HELI 2 (raider_heli_passive) [gotoTarget]- WARN: unable to find target...
LOG  : General     , 1694575396410> 635,666,908>  - EHE: ERR: HELI 2 (raider_heli_passive) [gotoTarget] no target in updateEvent()
LOG  : General     , 1694575396410> 635,666,908>  - EHE: ERR: HELI 2 (raider_heli_passive) [gotoTarget] no trueTarget in updateEvent()
LOG  : General     , 1694575396411> 635,666,909> EHE: HELI 2 (raider_heli_passive) [gotoTarget]  -no target + arrived
LOG  : General     , 1694575396411> 635,666,909>  -- EHE: IsoPlayers adding:Isaac Ellison
LOG  : General     , 1694575396412> 635,666,909>  -- [update]: HELI HELI 2 (raider_heli_passive) [gotoTarget] selecting targets <0> x
LOG  : General     , 1694575396412> 635,666,909>  --- HELI HELI 2 (raider_heli_passive) [gotoTarget]- WARN: unable to find target...
LOG  : General     , 1694575396612> 635,667,110>  - EHE: ERR: HELI 2 (raider_heli_passive) [gotoTarget] no target in updateEvent()
LOG  : General     , 1694575396612> 635,667,110>  - EHE: ERR: HELI 2 (raider_heli_passive) [gotoTarget] no trueTarget in updateEvent()
LOG  : General     , 1694575396613> 635,667,111> EHE: HELI 2 (raider_heli_passive) [gotoTarget]  -no target + arrived
LOG  : General     , 1694575396613> 635,667,111>  -- EHE: IsoPlayers adding:Isaac Ellison
LOG  : General     , 1694575396613> 635,667,111>  -- [update]: HELI HELI 2 (raider_heli_passive) [gotoTarget] selecting targets <0> x
LOG  : General     , 1694575396613> 635,667,111>  --- HELI HELI 2 (raider_heli_passive) [gotoTarget]- WARN: unable to find target...
LOG  : General     , 1694575396813> 635,667,312>  - EHE: ERR: HELI 2 (raider_heli_passive) [gotoTarget] no target in updateEvent()
LOG  : General     , 1694575396813> 635,667,312>  - EHE: ERR: HELI 2 (raider_heli_passive) [gotoTarget] no trueTarget in updateEvent()
LOG  : General     , 1694575396814> 635,667,312> EHE: HELI 2 (raider_heli_passive) [gotoTarget]  -no target + arrived
LOG  : General     , 1694575396814> 635,667,313>  -- EHE: IsoPlayers adding:Isaac Ellison
LOG  : General     , 1694575396814> 635,667,313>  -- [update]: HELI HELI 2 (raider_heli_passive) [gotoTarget] selecting targets <0> x
LOG  : General     , 1694575396814> 635,667,313>  --- HELI HELI 2 (raider_heli_passive) [gotoTarget]- WARN: unable to find target...
LOG  : General     , 1694575397010> 635,667,508>  - EHE: ERR: HELI 2 (raider_heli_passive) [gotoTarget] no target in updateEvent()
LOG  : General     , 1694575397010> 635,667,508>  - EHE: ERR: HELI 2 (raider_heli_passive) [gotoTarget] no trueTarget in updateEvent()
LOG  : General     , 1694575397011> 635,667,509> EHE: HELI 2 (raider_heli_passive) [gotoTarget]  -no target + arrived
LOG  : General     , 1694575397011> 635,667,509>  -- EHE: IsoPlayers adding:Isaac Ellison
LOG  : General     , 1694575397011> 635,667,510>  -- [update]: HELI HELI 2 (raider_heli_passive) [gotoTarget] selecting targets <0> x
LOG  : General     , 1694575397012> 635,667,510>  --- HELI HELI 2 (raider_heli_passive) [gotoTarget]- WARN: unable to find target...
LOG  : General     , 1694575397211> 635,667,709>  - EHE: ERR: HELI 2 (raider_heli_passive) [gotoTarget] no target in updateEvent()
LOG  : General     , 1694575397211> 635,667,709>  - EHE: ERR: HELI 2 (raider_heli_passive) [gotoTarget] no trueTarget in updateEvent()
LOG  : General     , 1694575397212> 635,667,710> EHE: HELI 2 (raider_heli_passive) [gotoTarget]  -no target + arrived
LOG  : General     , 1694575397212> 635,667,710>  -- EHE: IsoPlayers adding:Isaac Ellison
LOG  : General     , 1694575397212> 635,667,710>  -- [update]: HELI HELI 2 (raider_heli_passive) [gotoTarget] selecting targets <0> x
LOG  : General     , 1694575397213> 635,667,710>  --- HELI HELI 2 (raider_heli_passive) [gotoTarget]- WARN: unable to find target...
LOG  : General     , 1694575397413> 635,667,911>  - EHE: ERR: HELI 2 (raider_heli_passive) [gotoTarget] no target in updateEvent()
LOG  : General     , 1694575397413> 635,667,911>  - EHE: ERR: HELI 2 (raider_heli_passive) [gotoTarget] no trueTarget in updateEvent()
LOG  : General     , 1694575397414> 635,667,912> EHE: HELI 2 (raider_heli_passive) [gotoTarget]  -no target + arrived
LOG  : General     , 1694575397414> 635,667,912>  -- EHE: IsoPlayers adding:Isaac Ellison
LOG  : General     , 1694575397414> 635,667,913>  -- [update]: HELI HELI 2 (raider_heli_passive) [gotoTarget] selecting targets <0> x
LOG  : General     , 1694575397414> 635,667,913>  --- HELI HELI 2 (raider_heli_passive) [gotoTarget]- WARN: unable to find target...
LOG  : General     , 1694575397614> 635,668,112>  - EHE: ERR: HELI 2 (raider_heli_passive) [gotoTarget] no target in updateEvent()
LOG  : General     , 1694575397614> 635,668,112>  - EHE: ERR: HELI 2 (raider_heli_passive) [gotoTarget] no trueTarget in updateEvent()
LOG  : General     , 1694575397615> 635,668,113> EHE: HELI 2 (raider_heli_passive) [gotoTarget]  -no target + arrived
LOG  : General     , 1694575397615> 635,668,113>  -- EHE: IsoPlayers adding:Isaac Ellison
LOG  : General     , 1694575397615> 635,668,113>  -- [update]: HELI HELI 2 (raider_heli_passive) [gotoTarget] selecting targets <0> x
LOG  : General     , 1694575397615> 635,668,113>  --- HELI HELI 2 (raider_heli_passive) [gotoTarget]- WARN: unable to find target...
LOG  : General     , 1694575397813> 635,668,312>  - EHE: ERR: HELI 2 (raider_heli_passive) [gotoTarget] no target in updateEvent()
LOG  : General     , 1694575397813> 635,668,312>  - EHE: ERR: HELI 2 (raider_heli_passive) [gotoTarget] no trueTarget in updateEvent()
LOG  : General     , 1694575397814> 635,668,312> EHE: HELI 2 (raider_heli_passive) [gotoTarget]  -no target + arrived
LOG  : General     , 1694575397814> 635,668,313>  -- EHE: IsoPlayers adding:Isaac Ellison
LOG  : General     , 1694575397814> 635,668,313>  -- [update]: HELI HELI 2 (raider_heli_passive) [gotoTarget] selecting targets <0> x
LOG  : General     , 1694575397815> 635,668,313>  --- HELI HELI 2 (raider_heli_passive) [gotoTarget]- WARN: unable to find target...
LOG  : General     , 1694575398014> 635,668,512>  - EHE: ERR: HELI 2 (raider_heli_passive) [gotoTarget] no target in updateEvent()
LOG  : General     , 1694575398014> 635,668,512>  - EHE: ERR: HELI 2 (raider_heli_passive) [gotoTarget] no trueTarget in updateEvent()
LOG  : General     , 1694575398015> 635,668,513> EHE: HELI 2 (raider_heli_passive) [gotoTarget]  -no target + arrived
LOG  : General     , 1694575398015> 635,668,513>  -- EHE: IsoPlayers adding:Isaac Ellison
LOG  : General     , 1694575398015> 635,668,513>  -- [update]: HELI HELI 2 (raider_heli_passive) [gotoTarget] selecting targets <0> x
LOG  : General     , 1694575398015> 635,668,513>  --- HELI HELI 2 (raider_heli_passive) [gotoTarget]- WARN: unable to find target...
LOG  : General     , 1694575398210> 635,668,708>  - EHE: ERR: HELI 2 (raider_heli_passive) [gotoTarget] no target in updateEvent()
LOG  : General     , 1694575398210> 635,668,709>  - EHE: ERR: HELI 2 (raider_heli_passive) [gotoTarget] no trueTarget in updateEvent()
LOG  : General     , 1694575398211> 635,668,709> EHE: HELI 2 (raider_heli_passive) [gotoTarget]  -no target + arrived
LOG  : General     , 1694575398211> 635,668,709>  -- EHE: IsoPlayers adding:Isaac Ellison
LOG  : General     , 1694575398211> 635,668,710>  -- [update]: HELI HELI 2 (raider_heli_passive) [gotoTarget] selecting targets <0> x
LOG  : General     , 1694575398211> 635,668,710>  --- HELI HELI 2 (raider_heli_passive) [gotoTarget]- WARN: unable to find target...
LOG  : General     , 1694575398411> 635,668,909>  - EHE: ERR: HELI 2 (raider_heli_passive) [gotoTarget] no target in updateEvent()
LOG  : General     , 1694575398412> 635,668,910>  - EHE: ERR: HELI 2 (raider_heli_passive) [gotoTarget] no trueTarget in updateEvent()
LOG  : General     , 1694575398413> 635,668,911> EHE: HELI 2 (raider_heli_passive) [gotoTarget]  -no target + arrived
LOG  : General     , 1694575398413> 635,668,911>  -- EHE: IsoPlayers adding:Isaac Ellison
LOG  : General     , 1694575398413> 635,668,911>  -- [update]: HELI HELI 2 (raider_heli_passive) [gotoTarget] selecting targets <0> x
LOG  : General     , 1694575398413> 635,668,911>  --- HELI HELI 2 (raider_heli_passive) [gotoTarget]- WARN: unable to find target...
LOG  : General     , 1694575398613> 635,669,111>  - EHE: ERR: HELI 2 (raider_heli_passive) [gotoTarget] no target in updateEvent()
LOG  : General     , 1694575398613> 635,669,112>  - EHE: ERR: HELI 2 (raider_heli_passive) [gotoTarget] no trueTarget in updateEvent()
LOG  : General     , 1694575398614> 635,669,112> EHE: HELI 2 (raider_heli_passive) [gotoTarget]  -no target + arrived
LOG  : General     , 1694575398614> 635,669,112>  -- EHE: IsoPlayers adding:Isaac Ellison
LOG  : General     , 1694575398614> 635,669,113>  -- [update]: HELI HELI 2 (raider_heli_passive) [gotoTarget] selecting targets <0> x
LOG  : General     , 1694575398615> 635,669,113>  --- HELI HELI 2 (raider_heli_passive) [gotoTarget]- WARN: unable to find target...
LOG  : General     , 1694575398811> 635,669,309>  - EHE: ERR: HELI 2 (raider_heli_passive) [gotoTarget] no target in updateEvent()
LOG  : General     , 1694575398811> 635,669,310>  - EHE: ERR: HELI 2 (raider_heli_passive) [gotoTarget] no trueTarget in updateEvent()
LOG  : General     , 1694575398812> 635,669,310> EHE: HELI 2 (raider_heli_passive) [gotoTarget]  -no target + arrived
LOG  : General     , 1694575398812> 635,669,310>  -- EHE: IsoPlayers adding:Isaac Ellison
LOG  : General     , 1694575398812> 635,669,311>  -- [update]: HELI HELI 2 (raider_heli_passive) [gotoTarget] selecting targets <0> x
LOG  : General     , 1694575398813> 635,669,311>  --- HELI HELI 2 (raider_heli_passive) [gotoTarget]- WARN: unable to find target...
LOG  : General     , 1694575399013> 635,669,511>  - EHE: ERR: HELI 2 (raider_heli_passive) [gotoTarget] no target in updateEvent()
LOG  : General     , 1694575399013> 635,669,512>  - EHE: ERR: HELI 2 (raider_heli_passive) [gotoTarget] no trueTarget in updateEvent()
LOG  : General     , 1694575399014> 635,669,512> EHE: HELI 2 (raider_heli_passive) [gotoTarget]  -no target + arrived
LOG  : General     , 1694575399014> 635,669,512>  -- EHE: IsoPlayers adding:Isaac Ellison
LOG  : General     , 1694575399014> 635,669,513>  -- [update]: HELI HELI 2 (raider_heli_passive) [gotoTarget] selecting targets <0> x
LOG  : General     , 1694575399014> 635,669,513>  --- HELI HELI 2 (raider_heli_passive) [gotoTarget]- WARN: unable to find target...

**Additional context**
I have other mods installed but don't have the slightest idea what other mod could affect this one. Also, I'm playing on a dedicated server with friends.

**Comment by Chuckleberry-Finn** [comment]
Does the event get stuck or stay around for a really long time (as in more than a day in game?)

**Comment by Origichen** [comment]
Yeah it seems that way according to the logs. It'll spam that error so long as the server is up. A restart is usually what we have to do to fix it. 

Sometimes it's hard to tell if the event is still going since we wont hear the helicopter come by.

**Comment by Origichen** [comment]
Let me know if you need me to provide any more details to help with this.

**Comment by Origichen** [comment]
Any updates on this? My current workaround is to disable all of the helicopters that can potentially attack.

**Comment by Chuckleberry-Finn** [comment]
The issue would be any events that can hover. And no progress on it as I don't have time.

**Comment by oldmansutton** [comment]
I have this happening too, I think it's because it doesn't have a self:target, it then calls self:setTargetPos(), but setTargetPos() just returns if there's no self:target, so it's just a loop without end.  I'll continue to go through the code, and submit a pull request if I can find a fix.  Appreciate you, Chuckleberry.

**Comment by Chuckleberry-Finn** [comment]
Duplicate issue, see #269
