### ISSUE TITLE
does Expanded Heli mod is compatible Superb - Survivor?

### ISSUE THREAD

**Issue by localBasementdweller** [TEHE-Studios/ExpandedHelicopterEvents#234]
I have a small question if someone sees this, ive been playing in solo with superb - survivor mod i didnt see any event with helicopter i put all insane in the settings and still dont see anything maybe im a idiot but can someone tell me. (I also put never in sadistic director)

**Comment by Chuckleberry-Finn** [comment]
This is not an issue, and should be in discussion. I would have to guess you've set the start day beyond the helicopter scheduler.
