### ISSUE TITLE
So, i've been getting a glitch that makes the game entirely unplayable, when i turn on the mod the ui in the game just doesn't work, i've verified the files in the game and reinstalled it but it keeps happening.

### ISSUE THREAD

**Issue by PzUSER567** [TEHE-Studios/ExpandedHelicopterEvents#235]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Console logs:**
Console logs are stored in your local files. `OS:\Users\<username>\Zomboid\console.txt`
For single player (or connected players) the file is named `console.txt`, for hosts or servers the file will be named `coop-console` or `server-console`. *Include any relevant logs - do not cut or edit the log to make it smaller.*

**Additional context**

**Comment by PzUSER567** [comment]
mb, didn't mean to post this, i never used github

**Comment by sharkster91** [comment]
It's fine.
