### ISSUE TITLE
Mod doesn't let me play PZ if activated.

### ISSUE THREAD

**Issue by PzUSER567** [TEHE-Studios/ExpandedHelicopterEvents#236]
**Describe the bug**
So, i've been getting a glitch that makes the game entirely unplayable, when i turn on the mod the ui in the game just doesn't work, i've verified the files in the game and reinstalled it but it keeps happening,the menu animation keeps working ( thunder ) but nothing more.

**To Reproduce**
Just turn on the mod and, boom your menu / ui isn't showing wich doesn't let you play the game.

**Expected behavior**
Once activated it should look like the image below

**Screenshots**

![Captura de pantalla 2023-09-21 192653](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/assets/145704725/c8670419-7e82-4d82-8e56-9c6c35c972f3)

LOG  : General     , 1695317077466> EXITDEBUG: MainScreenState.enter 2
ERROR: General     , 1695317078772> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078774> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: ".0002"
ERROR: General     , 1695317078777> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078779> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078794> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078796> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078802> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078803> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078813> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078819> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078823> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078823> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078835> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078836> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078848> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078849> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078857> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078858> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078869> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078873> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078880> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078885> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078887> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078896> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078901> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078905> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078907> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078912> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078916> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078919> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078951> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078955> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078956> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078961> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078971> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078976> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078978> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078987> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078989> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
ERROR: General     , 1695317078992> ImportedSkeleton.collectBoneFrames> Could not find bone index for node name: "Body"
LOG  : General     , 1695317103289> UNKNOWN GLFW KEY CODE: 283
LOG  : General     , 1695317103289> UNKNOWN GLFW KEY CODE: 283
LOG  : General     , 1695317211944> UNKNOWN GLFW KEY CODE: 283
LOG  : General     , 1695317211944> UNKNOWN GLFW KEY CODE: 283

**Additional context**

**Comment by sharkster91** [comment]
No. We aren't causing it. Check one of the other 600 mods you have that are
currently adding in clothing.
