### ISSUE TITLE
 Not available

### ISSUE THREAD

**Issue by shedaxz** [TEHE-Studios/ExpandedHelicopterEvents#240]
so I tried to add it to my actual server on indifferentbroccoli, but ingame the mod shows as not available
jsut added the modID and workshopID abut in game shows this
![image](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/assets/147013310/8746e4ce-ae25-4590-8e00-73006abcb1ca)

I don't really know what to do and I kind of need help because it looks good and I would like to add it to the server, but it just shows as not available

**Comment by Chuckleberry-Finn** [comment]
You may not be adding the required mod.
