### ISSUE TITLE
Clarification on 'Continue Scheduler' option.

### ISSUE THREAD

**Issue by KateReller** [TEHE-Studios/ExpandedHelicopterEvents#242]
I am reading on how the 'Continue Scheduler' works, but I still cannot understand it.

So if I want helicopter events to keep happening forever, I enable 'Continue Scheduler'. This will make all events keep happening at their final stage one they reach them.

The part I am confused about is 'Continue Scheduler Late-Game Only'. Does selecting this option mean ONLY late game events will happen? Does that means that events like police and news are disabled on day one and only the late-game events will happen?
Or does it mean that all events will happen, but the early-game events will stop happening after a certain point but late game will keep on appearing?

**Comment by Chuckleberry-Finn** [comment]
'Early-game' events cease spawning when 'late-game' events begin being scheduled. Unselecting 'late-game-only' will make it so those events will continue to be scheduled alongside late game events. I'm aware the options are a bit confusing. May change it later down the line.
