### ISSUE TITLE
.

### ISSUE THREAD

**Issue by VlaD45454** [TEHE-Studios/ExpandedHelicopterEvents#254]
no menu. After installing the mod, all buttons in the main menu completely disappear. DEBUG: General     , 1698595909624> LoggerManager.init                  > Initializing...
LOG  : General     , 1698595909726> cachedir set to "C:\Users\0_0\Zomboid" ![Снимок экрана (26)](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/assets/149321231/caac1e26-3010-4c57-b229-f91f102aa198)

**Comment by sharkster91** [comment]
What an incredibly detailed report. Its almost like you have one hundred other mods loaded.
