### ISSUE TITLE
Flare gets stuck on player when using 'Grab and Drop' mod.

### ISSUE THREAD

**Issue by KateReller** [TEHE-Studios/ExpandedHelicopterEvents#255]
**Describe the bug**
Flare gets stuck on player when using 'Grab and Drop' mod.

**To Reproduce**

* Get signal flare.
* Ignite the flare, causing it to make a glow on the ground
* Wait until you can see the grab icon over an invisible item in the center of the flare.
* Player grabs the invisible item and the flare now follows their position.

**Expected behavior**
The player shouldn't be able to pick up the invisible item that makes the red glow.

**Screenshots**
[A video showing the after effects.
](https://streamable.com/7gmpno)

**Console logs:**
[Debug logs.](https://mclo.gs/eOaldd8)
[Log that had the word 'flare' in it.](https://mclo.gs/bEk5fGQ)

**Comment by sharkster91** [comment]
Not interested in patching someone else's mod. They can fix it on their end.
