### ISSUE TITLE
Voicelines hard to understand

### ISSUE THREAD

**Issue by ethantmc** [TEHE-Studios/ExpandedHelicopterEvents#259]
Very much a me problem I guess, but it's hard to understand the voice lines from the blue (Police?) helicopter events. If nothing can be done to provide accessibility for this (subtitle text on player, list of events/explanations so I can pause and figure it out), it'd be nice just to know what sound setting it's tied to so I can boost the hell out of it for the duration of events. 

This is mostly just a problem because I know there are events I'd want to flare for, but I don't know what they are (yet) and I figure the voice lines might be helpful for that.

**Comment by Chuckleberry-Finn** [comment]
Voice lines may be redone after B42, in the meantime the colors of the UI symbol can give away what kind of event it is.
