### ISSUE TITLE
Helicopter Event Not Spawning [MP]

### ISSUE THREAD

**Issue by LagGaming** [TEHE-Studios/ExpandedHelicopterEvents#260]
**Describe the bug**
The Expanded events are not spawning on my mp server. It was added later into the game and has yet to work. I added the config into the correct LUA. The vanilla event keeps happening instead. Checking the log and I see that the mod is loading when the server starts but it doesn't spawn.

**Console logs:**
[209.192.162.210_28017_fs_server-data_server-console.txt.pdf](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/files/13369890/209.192.162.210_28017_fs_server-data_server-console.txt.pdf)

**Comment by Chuckleberry-Finn** [comment]
The default settings for the event scheduler will cut off at 90 days. You'll need to modify the sandbox settings to account for on-going games.

**Comment by LagGaming** [comment]
I turned "ContinueScheduling =" to true, if my server is theoretically 200 days in should I set the "SchedulerDuration" to higher than 200?

**Comment by Chuckleberry-Finn** [comment]
ContinueScheduling should allow for events to happen regardless of the other settings. That being said, weather also can have an impact.

**Comment by LagGaming** [comment]
I will let you know if it is fixed.

**Comment by LagGaming** [comment]
it is fixed. thank you!

**Comment by SingleRanger** [comment]
I ran into a similar problem recently.
**Describe the bug**
The Expanded events are definitely not spawning on my mp server or appearing on the debug mode. I added it at the start of my mp game through the "Host" option and has yet to work. I also added the config into the correct LUA and the vanilla event keeps happening as well for 1 in game month.  Weirdly, when i check the sandbox option after i shut down the hosted server, my sandbox option were reset to the defaut setting (i'm really clueless about this part). So i went and check in single player and it work just fine.
**My list of mod i do for testing on mp**
![Project Zomboid Screenshot 2023 11 24 - 04 20 37 97](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/assets/151876962/eb8b1bd1-f014-4e9a-af06-5d394ad41d60)
![Project Zomboid Screenshot 2023 11 24 - 04 20 40 87](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/assets/151876962/ecf45c8a-1c77-4b69-aedf-19486e5f871d)

I even added the "ContinueScheduling" but for some reason it constantly reset to the default option after i saved the settings (i don't even know how to show it in real time but i swear it had happened)
**My test settings in the sandbox option**
![Project Zomboid Screenshot 2023 11 24 - 04 22 34 28](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/assets/151876962/8550abde-2021-4015-adcf-202dbbdffd1f)

**My test server log (please ignore some of the unloadable item from some other mods)**
[24-11-23_04-22-54_DebugLog-server.txt](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/files/13453520/24-11-23_04-22-54_DebugLog-server.txt)

Up until Oct this year, my experience with the mods in mp haven't had any problem so i really wonder what went wrong.
