### ISSUE TITLE
Thousands of errors at once

### ISSUE THREAD

**Issue by mixaloo** [TEHE-Studios/ExpandedHelicopterEvents#263]
**Describe the bug**
After starting a new save, the game freezes for a minute or two and errors generate in thousands, after that it's impossible to play because after a few seconds of walking the same error generating in hundreds freezes the game. Even after pressing quit to menu, the errors keep generating in two's and prevent from saving, forcing me to end the game's process. Quitting to desktop seems to work fine.

**To Reproduce**
Start a new game with my mod list.

**Expected behavior**
I expected a stutter-free game.

**Screenshots**

![20231120024103_1](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/assets/50614483/a9048ff9-cda5-413e-9c0c-a59cfb327a1c)
![20231120024113_1](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/assets/50614483/88e4db99-67db-4d3e-b487-2bf08bb67ec8)
![20231120024121_1](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/assets/50614483/818a5e3d-3877-413c-82c3-62b2ada74f11)
![20231120024131_1](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/assets/50614483/f2f921ce-ac1c-4d50-b9b8-6db63a33ae65)

**Console logs:**
Can't upload the unedited file because:
![image](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/assets/50614483/fcfb6056-5e83-47b1-823c-77cab814e82a)
Here's a debug log instead:
[20-11-23_02-41-29_DebugLog.txt](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/files/13405431/20-11-23_02-41-29_DebugLog.txt)

**Additional context**
The game works just fine with EHE only. I turned off all the mods that showed some kind of error at least once earlier, and the problem persists.

**Comment by mixaloo** [comment]
Ok, it seems that Tsar's Common Library 2.0 is the mod conflicting, and after tweaking the load order it's still causing errors

**Comment by Chuckleberry-Finn** [comment]
Very odd that their mod is causing issues - neither have been updated for some time. Please verify your cache and confirm you're not using any mod packs.
