### ISSUE TITLE
MRE Model is massive

### ISSUE THREAD

**Issue by FlyingSquid96** [TEHE-Studios/ExpandedHelicopterEvents#268]
**Describe the bug**
The MRE model is absolutely huge when dropped

**To Reproduce**
Get MRE Packet, drop it, mre wrapper after its eaten does not have issues

**Expected behavior**
It to be a normal size so we could place it on the table

**Screenshots**
https://steamuserimages-a.akamaihd.net/ugc/2281699474465351294/2AF0A0C3919DBFFC142AA975AA7660171C190B78/

**Console logs:**
Honestly not sure where to look in the console files, but i have 2 and unsure which one was active during the mre bug, i'll send both

[08-12-23_00-00-41_DebugLog-server.txt](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/files/13613970/08-12-23_00-00-41_DebugLog-server.txt)
[07-12-23_22-10-16_DebugLog-server.txt](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/files/13613972/07-12-23_22-10-16_DebugLog-server.txt)

I can also send modlist if needed

**Comment by FlyingSquid96** [comment]
Can i add both me and my friend saw this aswell not just me

**Comment by FlyingSquid96** [comment]
Also server is rented not hosted locally ^

**Comment by Chuckleberry-Finn** [comment]
This is either already fixed or will be fixed in the pending update.
