### ISSUE TITLE
WARN: unable to find target...

### ISSUE THREAD

**Issue by Demellion** [TEHE-Studios/ExpandedHelicopterEvents#269]
```

LOG  : General     , 1703962260057> 9,986,950,117> EHE: HELI 4 (news_chopper_fleeing) [gotoTarget]  -no target + arrived
LOG  : General     , 1703962260058> 9,986,950,117>  -- EHE: IsoPlayers adding:scol west
LOG  : General     , 1703962260060> 9,986,950,119>  -- [update]: HELI HELI 4 (news_chopper_fleeing) [gotoTarget] selecting targets <0> x
LOG  : General     , 1703962260060> 9,986,950,119>  --- HELI HELI 4 (news_chopper_fleeing) [gotoTarget]- WARN: unable to find target...

```
Spams my server console each 0.5 seconds. 
Please fix that or add some sandbox option to suppress such spam.

Thanks.

**Comment by PulsarNeutronStar** [comment]
same issue here
i have about 34 MB of logs just from about 45 minutes.
Thats far from ideal. People reported lag and desync on the server.

**Comment by PulsarNeutronStar** [comment]
![grafik](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/assets/56258612/f22dd077-29a7-461f-9d62-3fd84f16fa01)
this is from a few days ago

**Comment by pyhamakkara** [comment]
Same issue here

>07.01 17:54:12 [Server] INFO LOG  : General     , 1704650052021> 8,846,392,252>  - EHE: ERR: HELI 1 (samaritan_drop) [gotoTarget] no target in updateEvent()
07.01 17:54:12 [Server] INFO LOG  : General     , 1704650052021> 8,846,392,252>  - EHE: ERR: HELI 1 (samaritan_drop) [gotoTarget] no trueTarget in updateEvent()
07.01 17:54:12 [Server] INFO LOG  : General     , 1704650052021> 8,846,392,252> EHE: HELI 1 (samaritan_drop) [gotoTarget]  -no target + arrived
07.01 17:54:12 [Server] INFO LOG  : General     , 1704650052021> 8,846,392,252>  -- EHE: IsoPlayers adding:Tony Lasagna
07.01 17:54:12 [Server] INFO LOG  : General     , 1704650052021> 8,846,392,252>  -- EHE: IsoPlayers adding:Ong Nocap
07.01 17:54:12 [Server] INFO LOG  : General     , 1704650052021> 8,846,392,253>  -- [update]: HELI HELI 1 (samaritan_drop) [gotoTarget] selecting targets <0> x 
07.01 17:54:12 [Server] INFO LOG  : General     , 1704650052021> 8,846,392,253>  --- HELI HELI 1 (samaritan_drop) [gotoTarget]- WARN: unable to find target...

**Comment by PulsarNeutronStar** [comment]
#239 

seems like this issue is around for a while with the mod maker not not being in the position to dedicate the time to it.

I'll see if i can set fine tune the params to avoid this, but if not i guess i have to remove the mod from the server sadly.

**Comment by Chuckleberry-Finn** [comment]
You can avoid it by setting the events that hover to never. You can review the preset file to see which those are. From memory News, and maybe one of the raider types.

And yeah there's a lot of moving parts to the mod, I'd need more time in my schedule to actually sit down for testing more than anything else.

**Comment by PulsarNeutronStar** [comment]
> You can avoid it by setting the events that hover to never. You can review the preset file to see which those are. From memory News, and maybe one of the raider types.
> 
> And yeah there's a lot of moving parts to the mod, I'd need more time in my schedule to actually sit down for testing more than anything else.

Thanks for the awnser.
If you could provide the exact lines needed for the sandbox.ini to avoid the issue, that would be highly apprechiated.

**Comment by Chuckleberry-Finn** [comment]
#233

**Comment by oldmansutton** [comment]
This isn't actually fixed, a workaround where turning off functionality is mentioned.  The functionality itself however is still broken, so why is it being marked as completed?

**Comment by Chuckleberry-Finn** [comment]
I am not able to reproduce the issue. Please provide more recent logs.

**Comment by oldmansutton** [comment]
Oh snap, my bad, will have to throw it on next time I wipe my server.  A little too far into the game right now to throw it in now.  Thanks Chuckleberry-Finn for your work!
