### ISSUE TITLE
Feature for no crashes, would be great

### ISSUE THREAD

**Issue by IMadeAMod** [TEHE-Studios/ExpandedHelicopterEvents#271]
**Is your feature request related to a problem? Please describe.**
My problem is that when you play for a long time the area around your base will be littered by crashed helicopters and when you play with lowest loot ever the heli has way to much loot.

**Describe the solution you'd like**
An option to turn of crashed helicopters. ALL OF THEM! Weather doesnt matter.

**Describe alternatives you've considered**
Remove all the crashes for everyone. Even if they like it.

**Additional context**
This feature would be aimed at people who "never die" because they played this game waaay to much. The problem is that the amount of free loot and the amount of helis becomes problematic when you are able to survive for months/years whilst playing with lowest loot settings and mods that reduce the loot even more.

There are THREE helicopters next to my base. Like... 10 seconds of jogging. I would like the number to be 0. I am only a few months in and I will have to abandon the run if it doesnt stop.

The absence of this option breaks my game.

**Comment by Chuckleberry-Finn** [comment]
Thank you.
