### ISSUE TITLE
A problem of some sorts

### ISSUE THREAD

**Issue by kowatti** [TEHE-Studios/ExpandedHelicopterEvents#272]
**Describe the bug**
The events just zoom past. Barely can even see the little thing that points to the plane.

**To Reproduce**
I created a coop save and after that it hasn't worked even in singleplayer

**Additional context**
I cant tell if its because of the coop or an incompatible mod. I did put the vanilla helicopter event to never when i created the server. mb for worseish english

**Comment by Chuckleberry-Finn** [comment]
If it's zooming past it might just be a jet.
