### ISSUE TITLE
Sound effect copyright

### ISSUE THREAD

**Issue by Pleseebelt** [TEHE-Studios/ExpandedHelicopterEvents#278]
Hello, I am looking to develop a project (not for zomboid) that has similar themes and I wanted to incorporate some of the ideas brought in by Expanded Helicopter Events. I would like to ask permission for the use of some of the sound effects from the mod, or if you didn't create the sound effects, who the copyright holder is. Thank you.

**Comment by Chuckleberry-Finn** [comment]
The credits are included in the files or the filenames, the project has had a few iterations of sounds going into it. If there is no credit to a particular sound feel free to ask.

**Comment by Chuckleberry-Finn** [comment]
Going to close this as this is not an issue.
