### ISSUE TITLE
change helicopter icon on supply drop to cargo plane to fit lore

### ISSUE THREAD

**Issue by lebobby101** [TEHE-Studios/ExpandedHelicopterEvents#280]
in the game with default EHE settings supply drop happen while the chaos spreads to the world, then having helicopters drop supply drops to survivors in KY is wrong because at this point the whole world start to go to chaos, that's why i think having cargo planes dropping supplies on large distance across states would fit the lore better since loading an helicopter with supply wouldn't be resource  friendly in a "apocalypse going worldwide" setting
 
a chinook helicopter would also be more lore friendly and would not need a new sound, only a new icon

**Comment by Chuckleberry-Finn** [comment]
The late game supply drops are no longer FEMA, and are survivors trying to be helpful, and flying prop-planes. Their icons are a "plane" icon.
