### ISSUE TITLE
Vanilla helicopter event not working after removing this mod

### ISSUE THREAD

**Issue by dandark05** [TEHE-Studios/ExpandedHelicopterEvents#281]
**Describe the bug**
After we removed the mod from my hosted world, the vanilla helicopter event stopped working even if set to "sometimes" or "often". Is this mod safe to remove?

**To Reproduce**
Remove the mod from an exising hosted save and set vanilla event to "sometimes" or "often".

**Expected behavior**
I expected the vanilla event to work normally again.

**Screenshots**
Not the case

**Console logs:**
No error messages.

**Additional context**
I expected the vanilla event to work normally again. Is it possible?

**Comment by Chuckleberry-Finn** [comment]
When the mod is installed it changes the sandbox setting to never, but it also changes the start date to avoid issues.
So your next helicopter day is probably years later. I can fix this to not be an issue in the future.
