### ISSUE TITLE
Helicopter was failing to target either zombies or player (MP Dedicated Server)

### ISSUE THREAD

**Issue by TechSpartan24** [TEHE-Studios/ExpandedHelicopterEvents#282]
**Describe the bug**
Helicopter came in, started firing, ran inside as I was running inside noticed error numbers increasing quickly.
**To Reproduce**
Stand outside while helicopter flies by in area
**Expected behavior**
Either to be shot at or to watch zombies start dying

**Console logs:**
[console..txt](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/files/14275604/console.txt)

**Additional context**

**Comment by Chuckleberry-Finn** [comment]
Will be fixed in pending update.
