### ISSUE TITLE
Expanded Helicopter event is not working, and is not possible to spawn in Debug mode. 

### ISSUE THREAD

**Issue by SolidTDK** [TEHE-Studios/ExpandedHelicopterEvents#287]
**Describe the bug**
Expanded Helicopter event is not working, and is not possible to spawn in Debug mode. When i do spawn the Chopper, is just the vanilla one that comes (In -Debug) 
I will look forward to an fix to ur mod. Meantime i gonna remove it again

**Comment by SolidTDK** [comment]
Ok nvm. Im just an idiot. Who look the wrong place. Sorry

**Comment by Chuckleberry-Finn** [comment]
All good, those menus are not easy to understand right away.
