### ISSUE TITLE
Request for clearer description of what the scheduler entails

### ISSUE THREAD

**Issue by Lexyvil** [TEHE-Studios/ExpandedHelicopterEvents#288]
Hi! I suggest some clearer description on what "Scheduler" in the settings entail. I'm not sure if the default setting of 90 is the amount of days helicopter events can happen after world creation, or if it's meant to be the duration of how long helicopters/planes stay in the air for (in minutes? In hours?) once active. 

Thanks!
Loving this mod by the way, it's my favourite one alongside the AuthenticZ mod, and really hoping it'll be better/improved upon in v42.

**Comment by Chuckleberry-Finn** [comment]
Hello, the scheduler duration is the days events can be active.

**Comment by Chuckleberry-Finn** [comment]
https://github.com/TEHE-Studios/ExpandedHelicopterEvents/commit/1a047ddc1db3980dab668e28a799e89b134caaea
