### ISSUE TITLE
The server crashes and the console is full of some errors

### ISSUE THREAD

**Issue by Rmsiim** [TEHE-Studios/ExpandedHelicopterEvents#289]
The server crashes and the console is full of some errors
Here are the logs of the server where these problems occur
[14-03-24_23-42-21_DebugLog-server.txt](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/files/14615015/14-03-24_23-42-21_DebugLog-server.txt)
[13-03-24_23-04-59_DebugLog-server.txt](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/files/14615016/13-03-24_23-04-59_DebugLog-server.txt)

**Comment by Rmsiim** [comment]
With these errors players continue to play quietly, but why is this happening? But there have been complaints that the sound hangs for 2 game days, namely the sound of the helicopter, and now the server began to just hang, and then suddenly there is some kind of update and it falls after hanging, because of this I have to restart it, maybe I may not have set the sandbox settings correctly? hint what are the correct settings, we are in the game for 200 days.

Translated with DeepL.com (free version)

**Comment by Chuckleberry-Finn** [comment]
Can not replicate this issue at all.

**Comment by Rmsiim** [comment]
> Не удается воспроизвести эту проблему вообще.

But I sent you the logs from the server, then how best to configure the mod ?

**Comment by Chuckleberry-Finn** [comment]
Are the issues still happening?

**Comment by Rmsiim** [comment]
> Проблемы все еще возникают?

yes, It has a very strong impact and the server crashes.

**Comment by Rmsiim** [comment]
> Проблемы все еще возникают?

The server just hangs in the console, and then everyone kicks and in the console stop going logs and after about 10 minutes begins a flurry of errors and the server does not work and have to restart it, I even updated it with your new update and the use of 0

**Comment by Chuckleberry-Finn** [comment]
I've never had this issue before, and can't recreate it.
