### ISSUE TITLE
Expanded helicopter refuses to be enabled whenever i press it and cannot load into the game

### ISSUE THREAD

**Issue by Smartbics2** [TEHE-Studios/ExpandedHelicopterEvents#292]
**Describe the bug**
the mod simply refuses to be enabled or load up in my game....

**To Reproduce**
Steps to reproduce the behavior: uninstall the game whilst trying to uninstall another game unexpectedly and try to get back in your game asap before all mods are redownloaded

**Expected behavior**
it should be enabled in my game

**Screenshots**

**Console logs:**
Console logs are stored in your local files. `OS:\Users\<username>\Zomboid\console.txt`
For single player (or connected players) the file is named `console.txt`, for hosts or servers the file will be named `coop-console` or `server-console`. *Include any relevant logs - do not cut or edit the log to make it smaller.*

**Additional context**

**Comment by Smartbics2** [comment]
no matter HOW many times i try to enable this mod, IT NEVER enables

**Comment by Chuckleberry-Finn** [comment]
Apologies, I left some debugging stuff in there. Try waiting for steam to update the mod / resub to the mod to force a download.
