### ISSUE TITLE
Added Crash Multiplier to French Sandbox Translation File

### ISSUE THREAD

**Issue by Inkredibehl** [TEHE-Studios/ExpandedHelicopterEvents#293]
Hello.
I just saw your mod update and the new sandbox options but didn't find them in the FR Sandbox translation file.
So i made it myself. Here they are if you want to add them directly to your mod :)

Sandbox_ExpandedHeli_CrashChanceMulti = "Multiplicateur de Chances de Crash",
Sandbox_ExpandedHeli_CrashChanceMulti_tooltip = "Ceci est multiplié par le risque de crash, 0 empêchera tous les crashs.",

Sandbox_ExpandedHeli_AirRaidSirenEvent = "Transition des Raids Aeriens",
Sandbox_ExpandedHeli_AirRaidSirenEvent_tooltip = "Choisissez vrai si vous souhaitez qu'un événement d'alerte aérienne signale un passage d'événements de début de jeu moins difficiles à des événements de fin de jeu plus hostiles.",

Also, you can change the translation of 
Sandbox_ExpandedHeli_EventFEMA = "Drops d'Aide de la FEMA",
the actual translation not really has any sense ^^.

Thanks for your mod, i wouldn't play without !

**Comment by Chuckleberry-Finn** [comment]
Thank you!
