### ISSUE TITLE
Conflict between expand helicopter events and advanced G.E.A.R

### ISSUE THREAD

**Issue by vinilol467** [TEHE-Studios/ExpandedHelicopterEvents#298]
The conflict affects the item press bulletproofvest texture, i dont know if it affects something else
![image](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/assets/118195842/f4694ddc-1699-4196-b862-0ac0e75f3c36)
**To Reproduce**
have both mods enabled
**Console logs:**
[was not able to send the console text through git, says its too big](https://drive.google.com/file/d/1_1l1gBSyjisUMkWJ-lNU3VrbmHedKApf/view?usp=sharing)

**Comment by Chuckleberry-Finn** [comment]
Will be fixed in the next update.

**Comment by vinilol467** [comment]
TYVM
