### ISSUE TITLE
mod doesn't work for me 

### ISSUE THREAD

**Issue by MW9q** [TEHE-Studios/ExpandedHelicopterEvents#304]
**Describe the bug**
heli doesn't spawn 

**To Reproduce**
just wait

**Console logs:**
[console.txt](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/files/14922519/console.txt)

**Additional context**
nothing works except the radio and i have a lot of mods installed car mods and quality of life mods like better sorting and lots of map mods from the 120+ map collection so it's probably a conflict with another mod but it's not showing anything else except this mod in the error magnifier

**Comment by Chuckleberry-Finn** [comment]
Seems like something is breaking the target's position. Could you share more about your setup? Multiplayer? Number of players?

**Comment by MW9q** [comment]
3090
ryzen 5950x 
32g ram 
and i just play single player

**Comment by Chuckleberry-Finn** [comment]
I'm still not able to recreate this issue. Could you be subscribed to a modpack? If someone reuploaded the mod, it might be sitting in your local files.

**Comment by MW9q** [comment]
i have the 120+ maps mod pack and as i said only play single player or solo

**Comment by MW9q** [comment]
i did a clean install of the game deleted all mods and files and tried the vanilla ++ mod pack which I've seen videos of and the heli mod worked and the mod still had the same issue with radio working fine until the heli wants to spawn i see an error and it doesn't work

**Comment by MW9q** [comment]
tried to test the mod alone after clean installing again and it didn't work i'll put the console txt 
[console.txt](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/files/15039929/console.txt)
i'ts either my pc or the mod 
I don't know if this effects anything but i upgraded to win 11 recently and i didn't try the mod before upgrading

**Comment by MW9q** [comment]
hi, i still have the same problem even though you listed this issue as completed, did you find a solution?

**Comment by MW9q** [comment]
here is the console.txt , hope it helps 

[console.txt](https://github.com/user-attachments/files/18883688/console.txt)

**Comment by MW9q** [comment]
and this is what it looked like in the error magnifier

`function: getDistanceToXY -- file: ExpandedHelicopter01c_MainCore.lua line # 170 | MOD: [B41] Expanded Helicopter Events
function: launch -- file: ExpandedHelicopter01c_MainCore.lua line # 703 | MOD: [B41] Expanded Helicopter Events
function: eHeliEvent_engage -- file: ExpandedHelicopter06_EventScheduler.lua line # 51 | MOD: [B41] Expanded Helicopter Events
function: eHeliEvent_Loop -- file: ExpandedHelicopter06_EventScheduler.lua line # 339 | MOD: [B41] Expanded Helicopter Events
function: eHeliEvent_OnHour -- file: ExpandedHelicopter06_EventScheduler.lua line # 355 | MOD: [B41] Expanded Helicopter Events
java.lang.RuntimeException: __sub not defined for operands in getDistanceToXY
    at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:676)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
    at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
    at zombie.Lua.Event.trigger(Event.java:64)
    at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:92)
    at zombie.gameStates.IngameState.updateInternal(IngameState.java:1624)
    at zombie.gameStates.IngameState.update(IngameState.java:1333)
    at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:101)
    at zombie.GameWindow.logic(GameWindow.java:298)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:681)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`


really sorry if i'm being annoying but this mod looks really cool and it's a shame i can't even try it

**Comment by Chuckleberry-Finn** [comment]
When did you record this last log? Also looks like a partial log + I still can't recreate this issue.

**Comment by MW9q** [comment]
log was recorded 3 days ago same time i commented, you said before that the mod can't locate me or something like that, could you tell me what could cause that cuz as far as I've seen this issue is only happening to me so it could be my settings or something i did with the game files, if something like that could cause this issue, is there any way i can fix it

**Comment by MW9q** [comment]
The only mod pack I'm using now is the vanilla ++ by sophie

**Comment by Chuckleberry-Finn** [comment]
Not to get pedantic, but that is a collection of I'm not mistaken. A modPack would be what a server makes (usually without consent) where they reupload a bunch of mods. If you have any of those installed, it can cause issues.

**Comment by MW9q** [comment]
Also can my resolution fuck with the mod cuz I play on 1440 and there's a couple of mods that I know that don't work well on 2k or 4k

**Comment by MW9q** [comment]
tried the last 2 ideas i had which are the resolution the format and none of them solved this
