### ISSUE TITLE
Sandbox settings reverting when launching Multiplayer Server

### ISSUE THREAD

**Issue by nightbox69** [TEHE-Studios/ExpandedHelicopterEvents#311]
**Describe the bug**
Whenever I launch my MP Server for some reason my EHE settings will rewrite and revert itself from my SandBoxVars file.

I was writing my settings as verbose as it can be because it wasn't showing in the Sandbox Options from the server settings menu like this:
![image](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/assets/3726708/5dd55713-86d5-4cd3-819f-31a30ae7adda)

But it will turn into this after starting the server:
![image](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/assets/3726708/a45c8997-3bb4-48d3-97f3-b7bd32c386e0)

Disregarding that the comments might be an issue that will cause a rewrite simply changing anything from the automated settings (like ContinueScheduling to true or Frequency_jet to 5) will cause another rewrite back to their defaults. 

**To Reproduce**
Add the Sandbox Options of the mod on an already existing mutiplayer server and start the server. 

**Expected behavior**
I was expecting my sandbox settings to stick after I launch the server. 

**Console logs:**
I'm adding both console logs just to be doubly sure.
[console.txt](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/files/15179596/console.txt)
[coop-console.txt](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/files/15179598/coop-console.txt)

**Comment by nightbox69** [comment]
@Chuckleberry-Finn I have tried it with other mods disabled and it still does it. Apparently the workaround for the issue is for the host to enable the mod from the mod option in the main game menu then host, it'll activate the sandbox option for EHE. Might be a FAQ item instead.

**Comment by Chuckleberry-Finn** [comment]
I have seen that fix thrown around a bit, could the issue be due to formatting somehow?

**Comment by Chuckleberry-Finn** [comment]
Ah, I think the is an issue with some hosts. I'm not sure if there's an easy fix - maybe to manually set the file first?

**Comment by Chuckleberry-Finn** [comment]
The issue can be traced back to mods calling the single-player save function - which creates a `map_sand.bin` file. Just delete that file and the sandbox settings for MP should save.
