### ISSUE TITLE
Anti-cheat 21 kick players from server with EHE installed

### ISSUE THREAD

**Issue by Gustyboy** [TEHE-Studios/ExpandedHelicopterEvents#312]
**Describe the bug**
Anticheat 21 kicks players when they log in

**To Reproduce**
Have EHE installed on a dedicated server.

**Expected behavior**
I was expecting I could have the mod installed and running without deactivating anticheat 21

**Screenshots**
N/A

**Console logs:**
N/A

**Additional context**
It's a server with about 80-90 mods. Here is the full list of installed mods (you have to add SecretZ Pandemic & Operations + dependancies, it's not in the collection to avoid the server players spoils themselves).
https://steamcommunity.com/sharedfiles/filedetails/?id=3214877670

**Comment by Chuckleberry-Finn** [comment]
This anti cheat triggers from file mismatches. Not caused by this mod.
