### ISSUE TITLE
Maximum unlucky: 1. Not random stuff and 2. Helis crashing on rooftops.

### ISSUE THREAD

**Issue by ProIntegritate** [TEHE-Studios/ExpandedHelicopterEvents#313]
**Describe the bug**
1. Drops are pretty much the same thing. I've found 2 of the drops, the first one was all masks and CDC flyers. The second had lots of food in glas jars (which was better, but still).
2. Helicopter crashes on top of neighbours house. Couldn't access it at all.

**To Reproduce**
I dunno how to, play the game. Check the random number generator, it needs to be reseeded often

**Expected behavior**
1. Drops need to be random stuff and not just one thing.
2. It would be better if helis crashed on ground level.

**Additional context**
No other mod installed like this that conflict or would change behaviour, I'm only using smaller QoL mods.

**Comment by Chuckleberry-Finn** [comment]
Intended behavior for the most part. Roof top crashes shouldn't be occuring.
