### ISSUE TITLE
Heli dropped trash

### ISSUE THREAD

**Issue by DireHo** [TEHE-Studios/ExpandedHelicopterEvents#315]
I added the mod to an ongoing run. The first time the heli came by, it dropped a crate with a bunch of jars and some misc junk i can't remember. Some time goes by, I then tweaked the sandbox options to have the heli appear occasionally. 

Then, i had the issue where the container was dropping empty (about twice), and mostly on the same spot outside of my base. Tried reinstalling, moving the load order, couldn't get that to work. I have the vehicle repair overhaul mod, so dismantled the container, see if it reset something. Some days later, the heli comes by again and drops a bunch of trash right on my base-empty cans and bottles, broken bottles, no crate. I actually thought it was funny 😏 but i wonder if this is expected behavior or something got messed up?

**Comment by DireHo** [comment]
10/10 for the trash drops 😉

The only mod i can think of is Brita's weapon pack, as it has it's own loot rarity settings. Didn't fiddle with the numbers, at least not yet.  
I've been out of town on an expedition, will be going back to base soon. The mod is currently last in the load order. Since i'll be doing some R&R, i can use the sandbox options mod to increase the heli event frequency, see what happens. 

Bit off topic, i have a suggestion for the mod - reset time to normal when the event happens.

**Comment by Chuckleberry-Finn** [comment]
Pausing the game is on the to-do. 👍 

Let me know what happens.

**Comment by DireHo** [comment]
The heli came by yesterday while i was clearing the Knox prison, the crate had stuff on it - mostly empty jar boxes and uncooked food jars. No particularly useful items at this point, but at least there was something else other then an empty crate 😊 
It may still be worth waiting till i go back to base in Muldraugh and see what happens with another drop. Just hoping i don't get even more jars.

**Comment by DireHo** [comment]
Didn't have to go back to base. Got 2 more loot drops when out and about far from base, both had stuff in it. One thing i noticed, the crates consistently have jars, medical supplies and toilet paper. Lots of it. Are they supposed to drop something else, like... ammo, but at a very low chance?
Either way, looks like everything is fine 😊

**Comment by Chuckleberry-Finn** [comment]
The loot found from those kinds of crates are meant for "survival". The toilet paper is a gag on the fact it would be great realistically, but in game is kind of useless.
