### ISSUE TITLE
Mod started to crash after some time

### ISSUE THREAD

**Issue by Dnksh** [TEHE-Studios/ExpandedHelicopterEvents#316]
Some while ago this mod worked perfectly fine, but after I tried to install new weapon mod it has began to crash. When starting new game it showed 2 errors and game would stop respodning. Once I managed to make it work, but after loading save i got over 4000 errors so I switched back to vanilla firearms expansion but it still crashes.

**Comment by Chuckleberry-Finn** [comment]
Please follow the provided template.
