### ISSUE TITLE
Error when adding the mod mid game in MP

### ISSUE THREAD

**Issue by Tregedy** [TEHE-Studios/ExpandedHelicopterEvents#319]
Apparently the mod just refuse to work for some reason and i cant figure out why even after an hr of searching,the mod list alway say the mod is having errors and nothing but vanilla helicopter event would start
All the required mod alr been installed : easy config / errormag
Sadistic AI alr set to never
Perhap it due to mod load order?

![20240605224457_1](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/assets/171835463/4a723b38-13de-4d10-a503-c07bb68ed3d2)
[coop-console.txt](https://github.com/user-attachments/files/15593169/coop-console.txt)

**Comment by SilverShot00** [comment]
Same problem here
