### ISSUE TITLE
Soldier jumps out of helicopter before crashing.

### ISSUE THREAD

**Issue by Chennoid** [TEHE-Studios/ExpandedHelicopterEvents#335]
**Is your feature request related to a problem? Please describe.**
No, I dont believe so. 

**Describe the solution you'd like**
When a helicopter begins to crash, I would like a few (up to 3) soldiers to jump out of the plane before the helicopter fully crashes, additionally, with guns and equipment. When they fall onto the ground, they will turn and the player must find them.

**Describe alternatives you've considered**
Soldier corpses can be found in the cell where the helicopter crashed.

**Comment by Chuckleberry-Finn** [comment]
Events spawn crew members upon crashing - this is usually 1-3 people in most cases.
