### ISSUE TITLE
Recommendation: Specify pre-requisite mods in your workshop page (Easy Config Chucked)

### ISSUE THREAD

**Issue by PehSyCho** [TEHE-Studios/ExpandedHelicopterEvents#336]
Run a dedicated server for a group of friends and wanted to load this mod. Spent a small amount of time troubleshooting why the mod wouldn't load only to find that it was due to a missing pre-requisite mod "Easy Config Chucked". Having this in your mod description would have saved time for myself and likely others who have gone down this road.

**Comment by Chuckleberry-Finn** [comment]
![image](https://github.com/user-attachments/assets/9f84f1ee-68bc-4b8a-9510-05a2c2e564b3)
This is already a feature of Steam, and has been listed.
