### ISSUE TITLE
I can't use the signal flaer.

### ISSUE THREAD

**Issue by Thaumich** [TEHE-Studios/ExpandedHelicopterEvents#337]
**Describe the bug :**
When I first found the Signal Flaer in one of the boxes, I tried to use it, I got an error, I was playing with a friend. I thought that this was only in multiplayer and decided to check in a single game, the error was repeated, I don't know what to do.

**To Reproduce And a Video :**
Steps to reproduce the behavior: [Just try to use flare...](https://medal.tv/games/project-zomboid/clips/ipEkFIFArvalNl5M3/d1337GXrznmB?invite=cr-MSxVZ0UsMTc3MDY0NjM1LA)

**Console logs:**
COOP -> [coop-console.txt](https://github.com/user-attachments/files/16498734/coop-console.txt)

SINGLE -> [console.txt](https://github.com/user-attachments/files/16498735/console.txt)

**Additional context :**
I'm playing on a pirated version of the game, but I downloaded the mod from steam, so there shouldn't be any problems.

**Comment by Chuckleberry-Finn** [comment]
The logs only show an error for another mod that adds models to weapons. Could be you're using other mods that are causing conflicts.

**Comment by Thaumich** [comment]
> The logs only show an error for another mod that adds models to weapons. Could be you're using other mods that are causing conflicts.

hmm, maybe?

**Comment by Thaumich** [comment]
[console.txt](https://github.com/user-attachments/files/16522024/console.txt)
i tried again without mods, dont working again

**Comment by Chuckleberry-Finn** [comment]
Hi, your console log shows other mods are still installed, also the file that is causing the error is:

`ExpandedHelicopter_Flares(1).lua`

The file included with the mod does not have (1) next to it, that would imply it's a copy. Wherever you got your mods from is probably the cause, or you may have copied the files twice. Idk.

Can't really troubleshoot for so many unknown variables.
