### ISSUE TITLE
Should the mod even fire when Sandbox Option `Helicopter` set to never?

### ISSUE THREAD

**Issue by youkwhd** [TEHE-Studios/ExpandedHelicopterEvents#340]
**Is your feature request related to a problem? Please describe.**

When a player is setting the option `Helicopter` to never; in-game from the Sandbox Sadistic AI Director options, should this mod even function? I've had one game session and a helicopter icon popped out, and I was confused because the `Helicopter` option was disabled.

**Describe the solution you'd like**

From the file `shared/ExpandedHelicopter09b_SandboxOverride.lua`: abort/return from the function if `SandboxVars.Helicopter` is already disabled beforehand, set a global boolean like: `EHE_DISABLED = true` or, prefably `EHE_ENABLED = false`.

From the entry file (idk which) `server/ExpandedHelicopter06_EventScheduler.lua`, line 335:
```lua
-- I suppose this is the entry call that would start the events
--
-- Stop the eHeli events to occur if disabled
if not isClient() and EHE_ENABLED then
	Events.OnTick.Add(eHeliEvent_OnHour)
end
```

**Describe alternatives you've considered**

- Maybe _warn_ the player (from Steam workshop desc) that the mod will "always" set the helicopter event to be enabled, even though it's "disabled" from the Sandbox option?
- Add a new mod option (from in-game) to set something like: `Override Vanilla Helicopter Events: true`?

**Additional context**

I know that this problem can be **easily solved** by just disabling the mod (from Mods selection), but re-enabling, and re-disabling when you have tons of mod installed is a kinda tedious to do.

<br/>
<br/>

Also, if this would get implemented, could I be assigned to do the work? Thanks :)

**Comment by Chuckleberry-Finn** [comment]
I'm not sure I follow. If someone installs the mod why wouldn't it be enabling events to occur?

**Comment by Chuckleberry-Finn** [comment]
If I could safely hide that sandbox option I would. That being said, there is a section for the mod.
