### ISSUE TITLE
Helicopter Does Not Appear / Invisible

### ISSUE THREAD

**Issue by ShephardsLaw2** [TEHE-Studios/ExpandedHelicopterEvents#342]
**Describe the bug**
Helicopter does not appear when the event takes place.

**To Reproduce**
?

**Expected behavior**
I expected there to be a helicopter model, not just the shadow moving around the map.

**Screenshots**
![Designer](https://github.com/user-attachments/assets/16e0a17d-0693-4911-99b1-573ffe9b8308)
That green circle is the shadow of the helicopter, where the helicopter should be.

**Console logs:**
Apologies I could not find this in my local files on Steam, either it isn't there or I need to get my eyes checked.

**Additional context**
Mind you that this was tested on a new singleplayer server, the preset being Apocalypse with the only mods being enabled are EHE itself and its requirements like Easy Configs Chucked and the Error_Magnifier.

**Comment by Chuckleberry-Finn** [comment]
This is intended behavior.

**Comment by ShephardsLaw2** [comment]
> This is intended behavior.

So there is no helicopter?

**Comment by Chuckleberry-Finn** [comment]
> > This is intended behavior.
> 
> So there is no helicopter?

There is no visible model, yes.
