### ISSUE TITLE
News helicopter seems kind of nerfed compared to vanilla.

### ISSUE THREAD

**Issue by RayVee51** [TEHE-Studios/ExpandedHelicopterEvents#354]
As u saw in the title, the vanilla news heli is terrifying, however for the one in this mod leaves quickly when u're hiding.
Maybe make it like vanilla, hover around for half the day forcing you to stay in your base.

**Comment by Chuckleberry-Finn** [comment]
The goal of the mod was more to move zombies around, reward careful behavior, and not simply punish players for half a day. That being said, the hover time can be extended so they stay in the area longer.
