### ISSUE TITLE
Mod no MP não funciona 

### ISSUE THREAD

**Issue by SurvivorSalazar** [TEHE-Studios/ExpandedHelicopterEvents#357]
Eu crio um servidor MP, e não agenda os helicópteros, e sozinho funciona. Eu tenho todos mods requisitados instalados, e mesmo assim não agenda. Será que é porque eu coloco 12 meses depois do apocalipse? Realmente não sei qual o devido problema. Sou iniciante em criar server, se tem algo que precisa ser feito além de instalar os mods no MP , eu gostaria de saber. Sei que é meio vago sem eu dizer qual o erro, mas apenas não agenda helicóptero, só gostaria de saber se tem algo a mais que precisa ser instalado, ou alterado na pasta do server. desculpa minha ignorância e agradeço se puderem ajudar.

**Comment by Chuckleberry-Finn** [comment]
Check star day and other sandbox options, starting 12 months later on default settings = no events.
