### ISSUE TITLE
Disabling respawn of zombies

### ISSUE THREAD

**Issue by Mimir97** [TEHE-Studios/ExpandedHelicopterEvents#367]
Hey there guys.

First of all, I would like to say that I love your mod and the amount of stuff it brings to the table. I just have a small nitpick, as I am one of the players that disables the respawn off completely and instead uses the migration mechanics to balance the situation, I find the idea that the mod spawns zombies randomly through events in areas cleared (and sometimes walled-off bases) incredibly off-putting. Please, please make an option to disable respawn of the zombies as it ruins the imemrsion for me.

**Comment by Chuckleberry-Finn** [comment]
This mod does not spawn zombies (outside of a handful during crash events.)
