### ISSUE TITLE
[Suggestion] Make Helicopter Crashes able to be Dismantled

### ISSUE THREAD

**Issue by ArcAngelica** [TEHE-Studios/ExpandedHelicopterEvents#63]
There's doesn't seem to be a way to remove a helicopter crash from the world, had the unfortunate event where a helicopter crashed into me and my friends' base, and it's just there now, blocking the way, cannot be towed, cannot be dismantled, cannot be removed.

![108600_20220312001353_1](https://user-images.githubusercontent.com/42891286/158002053-8e5b9ecf-8571-4f98-8a3f-355229fdbb57.png)

**Please add the ability to Dismantle Crashed Helicopters** and their respective tails _(similar to Car Wrecks)_
If methods exist, please clarify them in the mod's page

*A possible workaround would be to make them despawn after enough days have passed

**Comment by N1GHTFOX90** [comment]
none of the parts can be dismantled because of the propane torch change

**Comment by ChuckTheSheep** [comment]
They should be able to be towed, and the propane changes will be reflected in a future update.

**Comment by N1GHTFOX90** [comment]
Ah yep, found a fix for the propane in the meantime, was able to tow them but could the vehicle recycle mod be used to dismantle them at some point?

**Comment by ChuckTheSheep** [comment]
We did recommend one of the dismantle mods but last I checked it broke with MP release.
