### ISSUE TITLE
Base game heli not overridden

### ISSUE THREAD

**Issue by NovaShrugs** [TEHE-Studios/ExpandedHelicopterEvents#83]
I'm in a solo game with the latest version, and the base game helicopter event was not overridden, there's no marker or anything.
[console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/9742269/console.txt)
(sorry for the insane amount of mods)

**Comment by NovaShrugs** [comment]
Happened again - 
[console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/9793146/console.txt)

**Comment by ChuckTheSheep** [comment]
Out of curiosity is this on a server or in single player? Did you go through sandbox?

**Comment by NovaShrugs** [comment]
I experience it in menu-hosted multiplayer and singleplayer, I've also witnessed it on a dedicated server, unsure about the dedicated server but I tinkered with sandbox settings for both menu hosted and singleplayer. I have events set to schedule forever if that helps any.

**Comment by NovaShrugs** [comment]
Where this particular issue took place is in singleplayer.

**Comment by ChuckTheSheep** [comment]
potential fix: d26beb4c00b95297b8dd56bacf1f6b6432feeccb

**Comment by ChuckTheSheep** [comment]
This should be addressed.
