### ISSUE TITLE
Unable to Start a Server with the mod.

### ISSUE THREAD

**Issue by Vistalgia** [TEHE-Studios/ExpandedHelicopterEvents#89]
This may seem like a duplicate post, but I can assure you—I had the exact same problem with the SMUI mod! Beneath are a completely different instance of the console.txt and the coop-console.txt, please check them out too!

[https://cdn.discordapp.com/attachments/921155789698256926/1043726958061690980/image.png](url)

[console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/10048400/console.txt)

[coop-console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/10048403/coop-console.txt)

Since the latest update, I have been unable to host my multiplayer server with this mod: **Expanded Helicopter Events**. I'll rundown what methods I've tried to get the mod running for my server and failed.

• By copying the mod ID folder from _Steam\steamapps\workshop\content\108600\2458631365_ over to my _Steam\steamapps\common\ProjectZomboid\steamapps\workshop\content\108600_ folder, I'd made sure that the server itself would have the **most** up-to-date version of the mod. After clicking **Host Game** and managing my server settings, etc., I hit **Start** and wait for a few seconds. I'm then caught with a **Server has stopped during launch (NormalTermination)** message above my screen and it throws me back out to the **Host Game** menu. No matter how many times I try to start it up, I am greeted by the same message.

• This was done in two ways: a control test consisting of the EHE mod by itself and my original full modlist that included EHE. Both servers were unable to begin.

• I was able to get past the **Host Game** menu with an absent **Server has stopped during launch (NormalTermination)**, by hosting a server without enabling EHE in the steam workshop section of the server settings.

• I have also sent over my server **save files** and **server settings** over to a friend who had subscribed to all the same exact mods, done everything in the same way as I did. They were able to host the server with the same save just fine without a **Server has stopped during launch (NormalTermination)** message.

• I unsubscribed to the mod, waited, then resubscribed. Verified my game as well. Same results as above.

• I also uninstalled the game itself (including the files that stayed), unsubscribed to every single mod, reinstalled with a fresh game, then subscribed to the mods. Same results as above.

**Comment by ChuckTheSheep** [comment]
Sorry for the delayed reply, It appears the server is trying to and failing to update the mod. I believe there should be a manifest file that you can delete to reset what mods have bene updated or not. There are a lot of people having issues with mods not downloading - the response I saw in the PZ discord tech_support thread was to "Wait for workshop, sometimes it takes a while". If I were you I would try to supply these logs to the tech_support channel as I don't believe there is anything I can do as a mod author.
