### ISSUE TITLE
Event isn't even running at all

### ISSUE THREAD

**Issue by Ferrets-JustFerrets** [TEHE-Studios/ExpandedHelicopterEvents#90]
Okay, for some reason, with all my previous runs, the Helicopter event doesn't seem to be spawning anymore at all. I don't remember what set of mods allowed it to run normally, but I haven't managed to fix it since. 

What I mean is the events aren't running, I mean that there are no helicopter sounds, no AEBS alerts, no FEMA drops either 

[console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/10159571/console.txt)

**Comment by Dendriticcell** [comment]
How many days has it been? For my Coop game it took about 5 or 6 days for the helicopters to start showing, although pretty late since Military helicopters don't say words and just shoot at anything that moves. But I still got Police helis and the casual jets

**Comment by Ferrets-JustFerrets** [comment]
Like, they don't seem to appear in single player at all

**Comment by Ferrets-JustFerrets** [comment]
Actually, they don't even spawn in on new saves, No helicopter sounds nor events occur, is there some way to reset it back to default settings or something

**Comment by ChuckTheSheep** [comment]
What are your sandbox settings for both the game and the mod?

**Comment by ChuckTheSheep** [comment]
This is single player? Your settings don't seem to be the issue.

**Comment by Ferrets-JustFerrets** [comment]
Yea, it is, maybe it's a mod conflict and I'm not sure why it's occurring, I'll try running these settings again and see if anything happens. I'll also record it

**Comment by Ferrets-JustFerrets** [comment]
Wait, is uncommon mean that there's not often helicopter sounds? I played a day with this mod and there's usually no helicopter sounds.

**Comment by Ferrets-JustFerrets** [comment]
Recorded it, had to put it into a youtube video, but yea, even with common settings, no sounds
https://youtu.be/9ewf2uxA-PM

**Comment by Ferrets-JustFerrets** [comment]
So I ran a different save, this time, the raider helicopter ran, but not the police nor military

**Comment by ChuckTheSheep** [comment]
It is not guaranteed to see all the event types depending on frequency. Default is still sparse depending on weather and luck.

Will be closing this issue for now.
