### ISSUE TITLE
Config not staying

### ISSUE THREAD

**Issue by TheMightyMcGrew** [TEHE-Studios/ExpandedHelicopterEvents#99]
Im trying to get this to work on an existing save on MP server. I downloaded both the expanded heli mod and the easy config chucked. The problem I think Im having is that whenever I try to input the config settings into the SandboxVars.lua it saves, I close and reopen to ensure it saved, and then as soon as I run the console to start the server it just resets that file back to before I pasted in the default config provided.

**Comment by Julleoa** [comment]
Same happening for me

**Comment by ChuckTheSheep** [comment]
What are you trying to save as the lua file?

**Comment by TheMightyMcGrew** [comment]
> What are you trying to save as the lua file?

Im not sure what you mean, but detailed desc. Of what i did, i opened the sandboxvars.lua file as written in your FAQ guide. Copied the default example, scrolled down to the bottom of the sandboxvars.lua and pasted it into a spot where the syntax lines up nicely. Then hit save.

**Comment by TheMightyMcGrew** [comment]
Ok so after a bit of thinking I wondered if you meant the file name or file type. When i open the file its name is exactly "servertest_SandboxVars.lua" and once I open and edit it with VS Code it gets saved as exactly the same

**Comment by ChuckTheSheep** [comment]
I mean it's contents. If there's a syntax issue it would cause the game to not use it.

**Comment by TheMightyMcGrew** [comment]
[servertest_SandboxVars.txt](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/files/10446016/servertest_SandboxVars.txt)
so imagine this is a .lua file since github doesnt support lua. I just copied this to another location and redefined it as .txt so i could post it. the original is in fact lua

**Comment by TheMightyMcGrew** [comment]
for searching purposes, the provided server config you posted is near the bottom of that file.

**Comment by chedaki** [comment]
Hello same problem here! Both in local hosted and online with gportal. Any ideas?

**Comment by RetroB** [comment]
Make sure you have both mods in Workshop and Mods in-game.

**Comment by ChuckTheSheep** [comment]
You can simply start the server and change sandbox options in game as an admin.

The mod needs to be in the workshop and mods section of your server setup.
